- dist/js/ui-components.js
- src/components/toolbar-menu/toolbar-button.html
Wrong `explorer` and `confirm-tb` in `toolbarButton`.
> Add explorer and confirm data to toolbar button

- dist/js/ui-components.js
- src/components/toolbar-menu/toolbar-button.html
- src/components/toolbar-menu/toolbar-view.html
When button has no icon, but image_url is present use this image_url instead of icon as img tag
> Add image icon to toolbar simple buttons

- src/toolbar/components/toolbar-menu/toolbar-button.html
- src/toolbar/components/toolbar-menu/toolbar-list.html
Matches margin used in toolbarList buttons
> Add right margin to toolbar button icons

- .travis.yml
- README.md
> Add Gitter support

- src/gtl/components/data-table/data-table.html
- src/gtl/components/data-table/dataTableComponent.spec.ts
- src/styles/ui-components.scss
This PR is the initial pass at reorganization and annotation of the stylesheet. It also renames "mig-*" prefixed classes to "miq-*"
> styling reorganization

- src/common/components/sortItemsComponent.ts
- src/site-switcher/site-switcher.html
- src/styles/ui-components.scss
- src/toolbar/components/toolbar-menu/toolbar-list.html
- src/toolbar/components/toolbar-menu/toolbarComponent.spec.ts
- src/toolbar/components/toolbar-menu/toolbarListComponent.spec.ts
https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes
> dropdown* - update to uib-dropdown

- demo/controllers/dataTableController.ts
- src/gtl/components/data-table/data-table.html
- src/gtl/components/data-table/dataTableComponent.ts
- src/gtl/components/index.ts
- src/gtl/components/pagination.html
- src/gtl/components/paginationComponent.spec.ts
- src/gtl/components/paginationComponent.ts
- src/gtl/components/tile-view/tile-view.html
- src/gtl/components/tile-view/tileViewComponent.ts
- src/gtl/interfaces/abstractDataViewClass.ts
- src/gtl/interfaces/dataTable.ts
Refactor pagination component so it will be one component holding all settings of pagination.
The API is:
| API value  | Description |
| ------------- | ------------- |
|  settings  |  Basic settings of pagination (sort by, titles, translate function and such)  |
|  sortBy  |  Sort by settings (Might be merge this into settings object)  |
|  perPage  |  Per page settings (Might be merge this into settings object)  |
|  onSelectAll  |  Function which is fired when select all is clicked  |
|  onChangeSort  |  Function which is fired when sort by or sort direction is changed  |
|  onChangePage  |  Function which is fired when page is changed  |
|  onChangePerPage  |  Function which is fired when number of items per page is changed  |
> Pagination component as standalone

- src/site-switcher/site-switcher.html
This is a fix for the siteswitcher not rendering the dropdown properly.
> Fix for issue with dropdown rendering

- src/site-switcher/site-switcher.html
This attribute was missing and it caused rendering of the component in SUI to not work properly
> Fix for menu layout issue on site switcher component

- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Fixing issue mentioned by @d-m-u in https://www.pivotaltracker.com/story/show/144481043/comments/176976267
/cc @himdel @martinpovolny
> Fix adding and removing entries

- bower.json
- package.json
Renamed package to scoped NPM package name and bumped it to next logical version number
> Renamed package and bumped version number

- .npmignore
- bower.json
- package.json
> Add npmignore and increase version

- package.json
- src/fonticon-picker/services/fonticonService.ts
- src/styles/vendor.scss
- webpack.vendor.config.js
- yarn.lock
* New font family called font fabulous in demo app
* Correct display of new font family in demo app
> Add font fabulous to build application, change service to work with all fonts families including font fabulous

- src/fonticon-picker/services/fonticonService.ts
Use of correct fetch of cssRules as suggested by @skateman and found by @AparnaKarve.
> Use cssRules instead of rules which is supported in all browsers

- demo/data/dialog-data-refresh.json
- src/dialog-user/components/dialog-user/dialogField.spec.ts
- src/dialog-user/components/dialog-user/dialogUser.spec.ts
- src/dialog-user/services/dialogData.spec.ts
> Create Unit tests for dialog-user component

- bower.json
- package.json
- src/dialog-user/components/dialog-user/dialogField.html
- src/dialog-user/components/dialog-user/dialogField.ts
- src/dialog-user/components/dialog-user/dialogUser.ts
- src/dialog-user/services/dialogData.ts
- src/styles/ui-components.scss
Fixes PV https://www.pivotaltracker.com/story/show/149929129
Auto refresh was not cascading changes
> Dialog component-  Auto refresh fix

- src/dialog-user/components/dialog-user/dialogField.spec.ts
> Updated Dialog component tests

- bower.json
- package.json
- src/dialog-user/services/dialogData.ts
> [Fixes #150175430] Fix typing for dialog values

- bower.json
- package.json
- src/dialog-user/components/dialog-user/dialogUser.spec.ts
- src/dialog-user/components/dialog-user/dialogUser.ts
> Added onInit function to Dialog component

- src/dialog-user/components/dialog-user/dialogUser.ts
> Set dialog data to save when dialog component is initialized

- src/dialog-user/components/dialog-user/dialogUser.ts
- src/dialog-user/services/dialogData.ts
- yarn.lock
> Fixed issue dialog component with fields not refreshing data appropriately

- src/toolbar/components/toolbar-menu/toolbar-button.html
> Toolbars: Support function and function-data for top-level buttons.

- .eslintrc.json
- package.json
> Added eslint linter

- src/tree-view/treeViewComponent.ts
The new `errorHandlers` binding allows us to set custom error handlers for various operations in the `TreeView`.
> Optionally pass an error handler for TreeView node selection

- src/dialog-editor/services/modal/modalService.ts
Updating `modalService` controller according to @karelhala's [suggestions](https://github.com/ManageIQ/ui-components/pull/139#discussion_r137266430)
Behaviour should not be changed
/cc @martinpovolny @karelhala
> Improved 'switch' statements implementation

- package.json
- yarn.lock
@himdel this `yarn.lock` thing is scaring me, can you please review?
> Use font-fabulous from the NPM repo instead of GitHub

- src/gtl/components/data-table/data-table.html
- src/gtl/components/data-table/dataTableComponent.spec.ts
- src/gtl/components/data-table/dataTableComponent.ts
In the future we want to favor images over icons and testing which item has which one is easier this way.
> Split up isIconOrImage helper function into hasIcon and hasImage

- src/styles/ui-components.scss
https://bugzilla.redhat.com/show_bug.cgi?id=1486618
Old
New
> Fix quad scrolling issue

- src/tree-selector/treeSelector.html
- src/tree-selector/treeSelectorComponent.ts
- src/tree-view/treeViewComponent.ts
Forgot this feature earlier :disappointed:
> Add tree persistence support for TreeSelectorComponent

- .github/CODEOWNERS
- src/dialog-user/components/dialog-user/dialogField.html
- src/dialog-user/components/dialog-user/dialogField.ts
- src/dialog-user/components/dialog-user/dialogUser.ts
- src/dialog-user/services/dialogData.ts
> Fixed bugs with dialog field validations

- src/tree-view/treeViewComponent.spec.ts
Just as a starter, more will come as I'll have some time to make them.
> Added initial specs for the treeViewComponent

- demo/views/dialog/user.html
- src/dialog-user/components/dialog-user/dialog.html
- src/dialog-user/components/dialog-user/dialogUser.ts
> Issue with Dialogs.   Refresh button not showing 

- src/dialog-editor/components/modal-field-template/tag-control.html
- src/dialog-editor/components/modal-field-template/text-area-box.html
- src/dialog-editor/components/modal-field-template/text-box.html
- src/dialog-editor/services/modal/modal.html
correction for bugs introduced in #170 
@eclarizio @himdel
> Fix missing association drop down

- src/dialog-editor/components/modal-box/box.html
- src/dialog-editor/components/modal-field/field.html
- src/dialog-editor/components/modal-tab/tab.html
Corrected modal titles for different types.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1511331
> Corrected modal names for different types

- src/tree-view/treeViewComponent.ts
Fixes https://github.com/ManageIQ/ui-components/issues/199
> Fix long lines causing compile fail in treeViewComponent.

- src/gtl/components/data-table/data-table.html
- src/gtl/components/data-table/dataTableComponent.spec.ts
- src/gtl/components/tile-view/tile-view.html
- src/gtl/components/tile-view/tileViewComponent.ts
- src/gtl/interfaces/abstractDataViewClass.ts
When clicking on button inside tile it will also call on row click. This PR fixes such issue and only triggers button click call.
https://bugzilla.redhat.com/show_bug.cgi?id=1518443
> Clicking on order button will call only button function and not row click function

- tsconfig.json
https://github.com/ManageIQ/ui-components/pull/77#discussion_r123964139
> Increase typescript stdlib 

- README.md
- scripts/.build.sh
- src/dialog-user/components/dialog-user/dialogUser.spec.ts
- src/dialog-user/services/dialogData.spec.ts
- correct command in README.md
- correct command in build script
@himdel PTAL
> Corrected command to run tests

- src/dialog-user/services/dialogData.spec.ts
- src/dialog-user/services/dialogData.ts
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1512398
> Fixed issue with Dialog field validation passing when no values selected

- src/dialog-editor/components/box/box.html
- src/dialog-editor/components/box/boxComponent.ts
- src/dialog-editor/components/toolbox/toolboxComponent.ts
- src/dialog-editor/services/dialogEditorService.spec.ts
- src/dialog-editor/services/dialogEditorService.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1514117
> Adding ordinal numbers to the dropped elements

- src/dialog-user/components/dialog-user/dialogField.html
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1519029
> Updated css class use for dialog checkboxes

- src/dialog-user/components/dialog-user/dialogField.html
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1519275
> Added Uniqe HTML ID attribute to dialog fields

- src/dialog-user/services/dialogData.spec.ts
- src/dialog-user/services/dialogData.ts
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1519358
> Service dialogs sorting

- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
- src/dialog-editor/services/dialogEditorService.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1516721
also fixes refreshing of fields after adding more entries.
Links:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3094
* https://github.com/ManageIQ/manageiq/pull/16680
* https://bugzilla.redhat.com/show_bug.cgi?id=1520001
/cc @karelhala
> Correct storing of default values for multi-select dropdown lists

- src/dialog-editor/components/toolbox/toolboxComponent.ts
- src/dialog-editor/services/dialogValidationService.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507754
> Validate presence of category attribute for Tag Control dialog field

- src/dialog-editor/components/field/field.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531316
issue was introduced in commit 9245795638b338b7fb5898a9ee9d407543b0bda4
> Corrected displaying of default value in Dialog Editor preview

- src/common/components/sortItemsComponent.spec.ts
- src/common/components/sortItemsComponent.ts
- src/gtl/components/data-table/data-table.html
- src/gtl/components/data-table/dataTableComponent.spec.ts
- src/gtl/components/tile-view/tile-view.html
This needs to be merged with https://github.com/ManageIQ/manageiq-ui-classic/pull/3293
https://bugzilla.redhat.com/show_bug.cgi?id=1536964
> Use header_text for rendering column and sorting headers

- README.md
To prevent ending up with errors
> Install dependencies before running tests

- src/dialog-editor/components/field/field.html
to keep in line with dialog-user change in https://github.com/ManageIQ/ui-components/pull/213
Cc @chalettu @romanblanco
> Dialog editor - remove .form-control from checkbox

- src/dialog-editor/services/dialogValidationService.spec.ts
- src/dialog-editor/services/dialogValidationService.ts
- Corrected naming for dialog elements for consistency
- Added test coverage for the validations
> Corrected labels for consistency

- src/dialog-user/components/dialog-user/dialogUser.ts
> BZ#1539871 - Fix for add to Shopping Cart being disabled

- src/gtl/components/data-table/data-table.html
..which the [corresponding ui-classic PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/3207) will use to detect misclicks around the checkbox
> gtl list - Add is-checkbox-cell class to td with checkbox

- src/dialog-editor/components/field/field.html
- src/dialog-editor/components/field/fieldComponent.spec.ts
- src/dialog-editor/components/field/fieldComponent.ts
- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-user/components/dialog-user/dialogField.html
- src/dialog-user/components/dialog-user/dialogField.spec.ts
- src/dialog-user/components/dialog-user/dialogField.ts
This should fix the major issue with https://bugzilla.redhat.com/show_bug.cgi?id=1531316, but while testing I found another issue when using multi-value dropdowns, and to fix that, we will need [this PR](https://github.com/ManageIQ/manageiq/pull/16978) from the main repo.
@romanblanco Please review
> Fix for default value on dropdown inside dialog not storing value

- demo/controllers/dialogEditorController.ts
- demo/views/dialog/editor.html
- src/dialog-editor/components/modal/modalComponent.ts
@romanblanco this binding is never being used anywhere...
> Drop the unnecessary visible binding from dialogEditorModal component

- src/dialog-user/components/dialog-user/dialogField.html
Fix for https://github.com/ManageIQ/manageiq-ui-classic/issues/3405
> Enabled select list to save values on change

- src/dialog-editor/services/dialogEditorService.spec.ts
- src/dialog-editor/services/dialogEditorService.ts
Introduced in #227, but definitely in a wrong place...moving it closer to the data loading.
\cc @eclarizio @romanblanco
> Move default value compensation to loadDialog in the DialogEditorService

- src/dialog-user/components/dialog-user/dialog.html
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1554259
> Removed label and description of dialog from dialog-user

- src/dialog-user/components/dialog-user/dialogField.html
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558271
> Track by $index ensures no duplicates in select list

- src/dialog-user/components/dialog-user/dialogField.ts
fixing codestyle after changes in https://github.com/ManageIQ/ui-components/pull/276
> Codestyle changes

- src/gtl/components/data-table/dataTableComponent.ts
Some smart message for @himdel
> Fix typo in data Table component

- src/dialog-editor/components/field/field.html
Prefixing all the things, based on [this guide](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes) so we can update to the latest angular-bootstrap.
@miq-bot add_reviewer @himdel 
@miq-bot add_label gaprindashvili/no, technical debt
> Prefix all angular-bootstrap directives with uib-

- src/dialog-editor/components/modal-field-template/check-box.html
- src/dialog-editor/components/modal-field-template/dynamic-values.html
- src/dialog-editor/components/modal-field-template/radio-button.html
- src/dialog-editor/components/modal-field-template/text-area-box.html
- src/dialog-editor/components/modal-field-template/text-box.html
`Show Refresh Button` and `oad values on init` options for dynamic dialog fields extracted to a separate file
response for suggestions from PR https://github.com/ManageIQ/ui-components/pull/303
@miq-bot add_label refactoring
@miq-bot add_reviewer @eclarizio 
@miq-bot assign @eclarizio 
/cc @himdel
> Extracted repeated code to a separate file

- src/dialog-editor/components/modal-field-template/drop-down-list.html
Follow-up PR for https://github.com/ManageIQ/ui-components/pull/305
DRYing up template files for Dialog Editor
@miq-bot add_label refactoring
@miq-bot add_reviewer @eclarizio
@miq-bot assign @eclarizio
> Using separate file for repeated options

- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1594301
> Added a functionality to sort dropdown values manualy

- README.md
I cannot remember to look at Wiki for instruction so I'm adding that info in README.md to save some time next time :) 
@miq-bot add_label gaprindashvili/no, documentation
> Add to README.md where to find instruction to release ui-components

- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Reverts ManageIQ/ui-components#311
> Revert "[GAPRINDASHVILI] Corrected description / values for dropdown list"

- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.spec.ts
- src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1597802
PR combines changes from #311 and #310 `gaprindashvili` into `master` branch.
- Added a functionality to sort dropdown values manualy (#310)
- Corrected description / values for dropdown list (#311)
- Specs
> Added a functionality to sort dropdown values manualy (master)

- src/dialog-user/components/dialog-user/dialogField.html
Fix for BZ # https://bugzilla.redhat.com/show_bug.cgi?id=1598455
> Fixed issue where options were being duplicated in dialogs

- package.json
- src/dialog-editor/components/field/field.html
- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/radio-button.html
- src/dialog-editor/components/modal-field-template/tag-control.html
- src/dialog-editor/components/modal/modalComponent.ts
- src/dialog-editor/components/toolbox/toolboxComponent.ts
- src/dialog-user/components/dialog-user/dialogField.html
- src/dialog-user/components/dialog-user/dialogUser.ts
- src/vendor.ts
> Add missing gettext annotations

- src/dialog-editor/components/modal/modalComponent.ts
- src/dialog-user/components/dialog-user/dialogUser.ts
- src/vendor.ts
Import `sprintf` and `__` where needed to make them work
> Sprintf and gettext fixes

- src/dialog-editor/components/modal-field-template/check-box.html
- src/dialog-editor/components/modal-field-template/date-time-control.html
- src/dialog-editor/components/modal-field-template/drop-down-list.html
- src/dialog-editor/components/modal-field-template/fields-to-refresh.html
- src/dialog-editor/components/modal-field-template/radio-button.html
- src/dialog-editor/components/modal-field-template/tag-control.html
- src/dialog-editor/components/modal-field-template/text-area-box.html
- src/dialog-editor/components/modal-field-template/text-box.html
> Add translatable labels / titles for select and bs-switch

- locale/en/ui-components.po
- locale/es/ui-components.po
- locale/fr/ui-components.po
- locale/ja/ui-components.po
- locale/pt_BR/ui-components.po
- locale/zh_CN/ui-components.po
> Add updated main & language gettext catalogs

- locale/en/ui-components.po
- locale/es/ui-components.po
- locale/fr/ui-components.po
- locale/ja/ui-components.po
- locale/pt_BR/ui-components.po
- locale/zh_CN/ui-components.po
This one is for gaprindashvili only.
> [GAPRINDASHVILI] Update main & language catalogs for gaprindashvili

- src/gtl/components/pagination/paging.html
I guess this could also go into gaprindashvili.
https://bugzilla.redhat.com/show_bug.cgi?id=1495630
> Add translate to paging label

- src/dialog-editor/services/dialogValidationService.spec.ts
- src/dialog-editor/services/dialogValidationService.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1488579
> Verification for specified entry point in dynamic dropdown added

- locale/ui-components.pot
- scripts/validate-gettext-catalog.js
- src/dialog-user/components/dialog-user/dialogField.html
* allow angular expressions in gettext strings
* fix i18n in `dialogField.html`
* update gettext catalog
gaprindashvili/no (I'll create a separate PR for gaprindashvili).
> Update gettext catalog and catalog validation

- locale/ui-components.pot
- scripts/validate-gettext-catalog.js
- src/dialog-user/components/dialog-user/dialogField.html
* allow angular expressions in gettext strings
* fix i18n in `dialogField.html`
* update gettext catalog
> [GAPRINDASHVILI] Update gettext string validation gettext fixes and update gettext catalog

- src/dialog-editor/components/field/field.html
- src/dialog-user/components/dialog-user/dialogField.html
Remove button styling from radio buttons 
Issue: #330
Before:
After
> Fix radio button styling

- scripts/.build.sh
> Add gettext:extract to travis build

- src/dialog-editor/services/dialogEditorService.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1557488
Moved the changes from PR https://github.com/ManageIQ/manageiq-ui-classic/pull/4153 to a more adequate position
> Setting default value for unset bootstrap switches

- src/dialog-editor/components/modal-field-template/text-area-box.html
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1620287
> Display complete instance Entry Point name

- src/dialog-editor/components/modal-field-template/tag-control.html
- src/dialog-editor/components/modal/modalComponent.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1614369
> Hide 'Single Value' checkbox if it is not applicable

- locale/es/ui-components.po
- locale/fr/ui-components.po
- locale/ja/ui-components.po
- locale/pt_BR/ui-components.po
- locale/zh_CN/ui-components.po
Spanish, French, Japanese, Brazilian Portuguese, Simplified Chinese.
https://bugzilla.redhat.com/show_bug.cgi?id=1592571
@simaishi
> [GAPRINDASHVILI] Add translations for gaprindashvili

- src/dialog-editor/services/dialogValidationService.ts
- src/tree-view/treeViewComponent.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1555170
> Added validation for entries type

- src/dialog-user/components/dialog-user/dialogField.html
- src/dialog-user/components/dialog-user/dialogField.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1464243
datepicker component: https://github.com/angular-ui/bootstrap/tree/master/src/datepicker
> Past days selection in date control fields corrected

- src/common/filters/abbrNumberFilter.ts
- src/vendor.ts
- webpack.config.js
- webpack.vendor.config.js
This replaces https://github.com/ManageIQ/manageiq-ui-classic/pull/5603/commits/719b0d5daaa076192e7c546a5879784343783ea1
@miq-bot add_label hammer/no, technical debt, changelog/no, dependencies
> Untangle numeral

- src/tree-view/treeViewComponent.ts
When collapsing a lazily-loaded node in an explorer tree, the state is not being stored in the `sessionStorage`. Therefore, if you do a full page reload, the collapsed node will be expanded again. The solution is to store the collapsed state in the `sessionStorage` as `false` for the given node. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1718457
@miq-bot add_reviewer @himdel 
@miq-bot add_label bug, hammer/yes
> Store collapsed nodes in tree state and reflect it upon rendering

- demo/controllers/dataTableController.ts
- demo/data/data-table.json
**BEFORE**
**AFTER**
Also sorting has been fixed
> fix data table demo: column headers and sorting

- src/dialog-user/services/dialogData.ts
reaction on https://github.com/ManageIQ/ui-components/pull/414#issuecomment-528266646
> Remove code dealing with default value for Tag Control

- .travis.yml
- README.md
- package.json
Issue:https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
> Update Node Version to 14

- src/dialog-editor/components/validation/validation.html
- src/dialog-user/components/dialog-user/dialogField.spec.ts
- src/dialog-user/services/dialogData.spec.ts
- src/dialog-user/services/dialogData.ts
[issue](https://github.com/ManageIQ/manageiq/issues/21567)
Before merging this one, we need to merge this [PR](https://github.com/ManageIQ/manageiq-schema/pull/643).
Dependent PRs
-----------------
https://github.com/ManageIQ/manageiq/pull/21792
https://github.com/ManageIQ/manageiq-schema/pull/643
> Add support message for regex

- .github/workflows/ci.yaml
> Update GHA versions

- src/dialog-editor/components/tree-selector/tree-selector.html
Related:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/9085
> Fix Embededded Typos

- .dockerignore
- .gitignore
- Dockerfile
- bin/build
@agrare Please review.
I verified this all manually and it all works (even all the way up to publishing, but when it did the publish I just did a Ctrl-C when it asked for the OTP.
> Add a Dockerfile for building the ui-components package
