README.adoc, package.json
This so we can utilize the latest ES6 in our build process without using Babel for transpiler for webpack builds in infrastructure. 
_NOTE: this only relevant to dev build and doesn't effect the runtime js components generated._
Version 5 is already deprecated and version 6.3.1 is the current version. Version 4 will be replaced with version 6 on Long Term Support(LTS) in October. The [LTS schedule](https://github.com/nodejs/LTS) is as follows:
=> Use the current Node.js version 6.x in our dev build environment. 

demo/controllers/toolbarMenuController.ts, dist/js/ui-components.js, jsdoc-conf.json, src/components/toolbar-menu/toolbar-button.html, src/components/toolbar-menu/toolbar-list.html, src/components/toolbar-menu/toolbar-menu.html, src/components/toolbar-menu/toolbarComponent.ts, src/filters/index.ts, src/filters/stateAndView.ts, src/index.ts, src/interfaces/toolbarType.ts, webpack.config.js
Explorer's toolbar contains two state buttons, so we have to enable these buttons and show them properly on toolbar.
These two state buttons uses `miq-button` component and set's specific classes (activate, disabled). We have to filter out `view` items from these two state buttons since they use same toolbarItem type.
New separators inside dropdown buttons.
Enable strict mode in webpack so the `npm` commands will not throw errors [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode).
=> Toolbar explorer

dist/js/ui-components.js, src/services/toolbarSettingsService.ts
When new toolbar is created we have to reset counter for number of selected items.
=> Reset countSelected after new toolbar object

dist/js/ui-components.js, src/components/toolbar-menu/toolbar-view.html, src/components/toolbar-menu/toolbarViewComponent.spec.ts
Without this, all the view toolbar items are blue, all the time, as of ManageIQ/manageiq#11020
Updated the view toolbar to match https://www.patternfly.org/pattern-library/content-views/list-view/
Cc: @karelhala, @skateman, @martinpovolny 
You can test by doing `bower install manageiq-ui-components=himdel/ui-components#fix-pf-310` under `manageiq/`
=> ToolbarView - update html to match patternfly 3.10

.build.sh, .travis.yml
New travis build config file, we now just have to enable travis builds for ui-components.
This travis build is trivial, specifies node and npm versions, before running build script it will install necessary dependencies.
Build script will just install this application and runs tests for it.
=> Add travis build file with build script

README.md, dist/js/ui-components.js, src/common/components/index.ts, src/common/components/sortItemsComponent.spec.ts, src/common/components/sortItemsComponent.ts, src/common/index.ts
This component is helper component for `pf-sort` it uses [patternfly's implementation](http://angular-patternfly.rhcloud.com/#/api/patternfly.sort.directive:pfSort) and just filter out items from header columns for gtls.
=> Sort component

dist/js/ui-components.js, src/toolbar/components/toolbar-menu/toolbarComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarComponent.ts
Fixes blank `miq-toolbar-group` if there are no items in button select. New test case to check this.
https://github.com/ManageIQ/ui-components/issues/23
=> Add checking for empty items in button select

scripts/.coverage.sh
Introduced in #29, `coverage.sh` is not run with CWD=scripts/, causing it to fail - fixed by changing to the right directory first..
@karelhala can you..? :)
=> coverage.sh - cd to scripts before assuming ../node_modules

src/toolbar/services/toolbarSettingsService.ts
The toolbar needs to know how many items are currently selected to be able to enable/disable items with the `onwhen` attribute.
Previously, this was done by calling checkboxClicked which increments/decrements the counter, but that can sometimes lead to inconsistent state (like toolbarCount going to -2).
Adding a method to simply set the counter, since we already do the counting in miq anyway.
Cc @karelhala , @martinpovolny
=> toolbarSettingsService - add setCount method, to replace checkboxClicked

package.json
postinstall is not only called after `npm install`, but also after having installed the package
prepublish is called only before publish *and* on doing a standalone `npm install`
So moving those actions to prepublish so that people using the package won't need typescript & typings, etc. Also removed bower install, because we can't assume that people using the npm package will even have bower..
I've already released a npm version of the package to be able to test, I'll do the bower thing after this is merged...
Cc @karelhala - any other thoughts where to put it?
=> npm - use prepublish instead of postinstall

README.md
Add a _Purpose_ section to the README.md and add **DevDependencies** and **Vulnerabilities** badges. Some people are confused as to what the repo should be used for (what kind of things belong here?). The Purpose section should eliminate some confusion there.
[Snyk.io](http://snyk.io) provides a dependency vulnerability database.
And the [BitHound](http://bithound.io) DevDependencies badge shows out of date and insecure DevDependencies (for the build). Bithound can be hooked into the CI as well: http://blog.bithound.io/bithound-101/
=> Documentation and Badge updates

src/dialog-editor/components/tab-list/tabListComponent.ts
Because of this mistake, it was impossible to close newly created tab in the dialog editor
=> Corrected object name for tabs sorting

bower.json
Since `ActionController` complains that `/assets/manageiq-ui-components/dist/css/ui-components.css.map` is missing we should ship map file for styles.
=> Enable map for main css file in bower distribution

.gitignore, bower.json, dist/css/ui-components.css.map
As @jzigmund mentioned in https://github.com/ManageIQ/ui-components/pull/66#issuecomment-299181036 `dist/css/ui-components.css.map` was still not present in distributed bower due to policy at Bower, that only one file with can be treated as main with given filetype [main-list](https://github.com/bower/spec/blob/master/json.md#user-content-main). So we do not ignore `.map` files in dist folder for github and also do not ignore whole folders `js` and `css` in `dist`.
=> Remove mapped files from gitignire

demo/data/toolbar.json, src/toolbar/components/toolbar-menu/toolbar-button.html, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbar-view.html, src/toolbar/components/toolbar-menu/toolbarComponent.spec.ts
closes #84 
As requested toolbar items should be colored based on JSON property `color` for each item.
Buttons, dropdown lists and dropdown items are colored by this property. Separators are **not** colored.
Color property can be hexa number with hash in it and text corresponding to such color.
=> Toolbar color

src/common/translateFunction.ts, src/dialog-editor/components/box/boxComponent.ts, src/dialog-editor/components/tab-list/tabListComponent.ts, src/dialog-editor/components/toolbox/toolboxComponent.ts, tsconfig.json
This PR fixes errors which were shown in console if any phase of build was ran (`npm run build` or `npm start`). Helper function was introduced, which checks if `__` exists on window object and if it does not exists it will return string which was passed to it, if it exists it will return result of `__(translateString)`.
No UI changes.
=> Clean build process so there are no more errors with missing __ function

tsconfig.json
In an effort to not allow bad stuff into the build this flag will not compile the bad stuff. I'm seeing on other typescript projects that things get committed even though they raise compile errors (this should not be allowed IMO). Keeps it clean from the start.
wdyt?
=> NoEmitOnError flag for typescript compiler.

src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts, src/dialog-editor/services/modal/modalService.ts
fixed issue described by @d-m-u in https://www.pivotaltracker.com/story/show/144481043/comments/177154253
There was a change in API. We're not using numbers for id's anymore, but strings.
Thanks for help, @himdel!
/cc @martinpovolny
=> Fixed resolving entries

src/fonticon-picker/components/fonticon-picker/fonticon-picker.html, src/fonticon-picker/components/fonticon-picker/fonticonPickerComponent.ts
For being able to use `miq-observe` with non-angular forms. @karelhala
=> Add function binding for fonticon picker onchange handling

src/gtl/services/dataTableService.spec.ts, src/gtl/services/dataTableService.ts
..because sometimes, the list of record ids is simply too long to fit in a GET request.
(For example, go to the list of VMs, switch to 1000 per page, select them all, and do Configuration > Set Ownership.)
Do not merge before ManageIQ/manageiq-ui-classic#1833.
=> GTL - fetchData - use post instead of get

src/dialog-editor/components/field/field.html, src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts, src/dialog-editor/components/modal-field-template/radio-button-drop-down-list.html
Selecting `Default value` for radio button should now work correctly in the modal and also in the preview:
thanks for help with this one @karelhala! 👍
=> Fix radio buttons so it shows selected values correctly

src/fonticon-picker/services/fonticonService.ts
Regular expression for the rescue @karelhala 
**Before:**
**After:**
=> Fixed missing icons in the fonticon picker component

application-settings.js, demo/controllers/index.ts, demo/controllers/treeViewController.ts, demo/data/lazyTree.json, demo/data/tree.json, demo/services/availableComponentsService.ts, demo/views/tree-view/basic.html, package.json, src/index.ts, src/tree-view/index.ts, src/tree-view/treeViewComponent.ts, src/vendor.ts, yarn.lock
This is nothing but a wrapper around [patternfly-bootstrap-treeview](https://github.com/patternfly/patternfly-bootstrap-treeview/) to provide it as a component. In the future it should be rewritten without jQuery. It will be used on [left-side explorer screens](https://github.com/ManageIQ/manageiq-ui-classic/issues/1871) in the classic UI. For the more complex trees with checkboxes a new component will be created in the future.
**Usage:** 
```html
<miq-tree-view name="tree-name" reselect="bool" data="[]" lazy-load="func" on-select="func"></miq-tree-view>
```
The `data` should contain the tree nodes in the format specified by [patternfly-bootstrap-treeview](https://github.com/patternfly/patternfly-bootstrap-treeview/#data-structure), the two callbacks functions should be in the following …
=> Wrapper component around patternfly-bootstrap-treeview for explorers

.gitignore, src/tree-view/treeViewComponent.ts
Added $timeout to treeview, so wrapper components don't have to lazy-load, and node-selected functions.
=> Added $timeout to tree-view functions

demo/controllers/treeViewController.ts, demo/views/tree-view/basic.html, src/tree-view/treeViewComponent.ts
If you want to programmatically select a node from outside the component, simply set its `selected` attribute to an object that has some matching attributes with a node.
`<miq-tree-view ... selected="{key: 'something'}">`
@karelhala or @himdel
=> Add one-way binding for external tree node selection in treeView

src/tree-view/treeViewComponent.ts
Missed [this parameter](https://github.com/patternfly/patternfly-bootstrap-treeview/#showimage) from the initial configuration of `bootstrap-treeview`.
=> Optionally display images as node icons in treeView

demo/controllers/treeViewController.ts, demo/data/lazyTree.json, demo/views/tree-view/basic.html, src/tree-view/treeViewComponent.ts
Sometimes we want to select a node that's not yet loaded. This is now possible by passing an array of node matchers in the `selected` attribute of the component. The first element of the array should match a node that's already available in the tree. The others should match its children, each in one level until the last element that matches the finaly node to be selected.
For example:
```json
[
{
"title": "Parent",
"nodes": [
{
"title": "Child",
"nodes": [
{
"title": "Grandchild"
}
]
}
]
}
]
```
If the tree above is lazily loaded on each level and you want to select the `Grandchild` node, you would need:
```html
<miq-tree-view ... selected="[{'title': 'Parent'}, {'title': 'Child'}, {'title': 'Grandchild'}]"/>
```
=> Allow to select a lazily loadable node in treeView

application-settings.js, demo/controllers/index.ts, demo/controllers/treeSelectorController.ts, demo/services/availableComponentsService.ts, demo/views/tree-view/tree-selector.html, src/index.ts, src/tree-selector/index.ts, src/tree-selector/treeSelector.html, src/tree-selector/treeSelectorComponent.ts
This is a wrapper component to treeView component.
It provides lazy load function to load partial data from passed Url, and parsing function, which marks some tree nodes as selectable, based on provided regExp.
There is also function which returns selected node.
```
<button ng-click="vm.openTreeView(!vm.showTree)">Toggle tree</button>
<tree-selector
ng-show="vm.showTree"
data="vm.data"
selectables="(^gc-)|(^lc-)"
display="vm.openTreeView"
on-select="vm.handleSelected(node)"
lazy-load="vm.getData"
>
</tree-selector>
```
* data: initial data for tree, shares the same format as [treeview](https://github.com/patternfly/patternfly-bootstrap-treeview)
* selectables: regular expression. this specifies which nodes in the tree can be selected
* display: function which handles showing/hiding tree
* …
=> Added tree selector component

src/tree-selector/treeSelector.html, src/tree-view/treeViewComponent.ts
This is the standard behavior in MiQ trees, if a node is selected it can't be unselected by clicking on it. This caused issues in the `TreeSelector` but it has been fixed by enabling `reselect`.
cc @Hyperkid123
=> Prevent unselection of an already selected node in TreeView

src/tree-view/treeViewComponent.ts
Do not render the tree until its `data` attribute is set. This will allow us to lazily load the tree after the component has been displayed.
=> Do not render the TreeView before it receives the node data

src/dialog-editor/services/dialogValidationService.ts, src/dialog-editor/services/index.ts
taking the method from PR https://github.com/ManageIQ/manageiq-ui-classic/pull/2055 as a new service for Dialog validations:
> 
> After these changes, it won't be possible to submit invalid dialog.
> The methods are testing that
> 
> - dialog has a name
> - dialog has at least one tab
> - every dialog tab have a name
> - every dialog tab has at least one box
> - every dialog box has a name
> - every dialog box has at least one element
> - every element has a name
> 
> if one test fails, the `Save` buttons becomes disabled.
> 
> Links
> ----------------
> * https://www.pivotaltracker.com/story/show/144481043
> 
> Steps for Testing/QA
> -------------------------------
> 
> Automation -> Automate -> Customization -> Edit this / Add a new dialog in the Dialog Editor -> [see the screencast]
> …
=> Dialog Editor Validations

demo/views/tree-view/basic.html, src/tree-view/treeViewComponent.ts
I extracted the miq-specific `key` attribute from the state storing part of TreeView. From now on if you want to store the tree state, you'd need to set the `persist` string parameter to a key that's uniquely set for each node in the `data`. In the miq-related context this should be `key`, but it basically can be anything. It was not necessary to store collapsed nodes in the session storage as they are always rendered as collapsed. So now it's possible to save the path to an expanded node instead of the `true` value that helps us in restoring the state of a lazily loadable node.
=> Improved state (re)storing for the TreeView component

demo/controllers/treeViewController.ts, demo/views/tree-view/basic.html, src/tree-view/treeViewComponent.ts
I thought we can avoid having this feature, but it seems like we're re-rendering the trees sometimes.
=> Allow reloading the TreeView if its data has been changed

demo/controllers/dataTableController.ts, src/common/components/sortItemsComponent.spec.ts, src/common/components/sortItemsComponent.ts, src/gtl/components/pagination/pagination.html, src/gtl/components/pagination/paginationComponent.spec.ts, src/gtl/interfaces/dataTable.ts, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbarListComponent.ts
`dropDownClass` (and `drop-down-class`) look like a typo, renaming to `dropdownClass` and `dropdown-class`.
Also making `dropdownClass` optional, since we always check before using, and don't always pass it in.
Cc @karelhala
=> Toolbar list - make dropDownClass optional, rename to dropdownClass

src/gtl/components/tile-view/tileViewComponent.ts, src/styles/ui-components.scss
the card could not access `tileCtrl.columns` because it has access only to the `pf-card-view` `config` object.
Adding `columns` to the config object so that it is available.
Also fixed the spacing a bit - there was no visual space between `dt` and `dl` (**Foo**:bar)
Cc @karelhala 
Infra provider - fine & now:
https://bugzilla.redhat.com/show_bug.cgi?id=1486702
=> tileView - fix columns to actually be available inside the card

demo/controllers/dialogEditorController.ts, demo/views/dialog/editor.html, src/dialog-editor/components/box/box.html, src/dialog-editor/components/box/boxComponent.ts, src/dialog-editor/components/field/field.html, src/dialog-editor/components/field/fieldComponent.ts, src/dialog-editor/components/tab-list/tab-list.html, src/dialog-editor/components/toolbox/toolbox.html, src/dialog-editor/components/toolbox/toolboxComponent.ts, src/dialog-editor/services/modal/modal.html, src/dialog-editor/services/modal/modalService.ts, src/styles/colors.scss, src/styles/dialog-editor-boxes.scss, src/styles/dialog-editor-toolbox.scss, src/styles/dialog-editor.scss, src/styles/ui-components.scss
Updated the Dialog Editor:
- Updated layout:  
- Dialog Name and Description as horizontal form 
- Toolbox on left, Tabs/Sections/Fields on right. 
- Added grab handles to toolbox items, boxes/sections, and fields/elements (appear on hover):
Toolbox Item:
Section:
Field:
- Added edit/pencil and remove/trashcan icons to Tabs, Sections, and Fields (appear on hover):
- Details Modal:
- Added component specific modal Titles Ex: "Edit Textarea Field" and "Edit Tab Details"
- Removed Delete button
- Replaced "box" terminology with "section"
Pivotal: https://www.pivotaltracker.com/n/projects/1613907/stories/150461077
@romanblanco 
@serenamarie125
=> Dialog Editor: Updated Styles

demo/controllers/treeSelectorController.ts, demo/views/tree-view/tree-selector.html, src/tree-selector/treeSelector.html, src/tree-selector/treeSelectorComponent.ts
I wanted to use the `TreeSelector` for catalog entry point selection in MiQ, but I realized that it's unusable. Here are some fixes:
* Handling the visibility of the tree moved out from the component
* Added support for data loaded after the component initialization
* Refactored the `matchSelectable` and `parseSelectable` functions
* Passing the `onSelect` method directly to the TreeView component
* Renamed `selectables` attribute to `selectable`
* Added the possibility to initially select a node using the `selected` attribute
* Reorganized public and private variables
* Created a more straightforward demo
@Hyperkid123 please take a look at this and try to understand the concept.
@himdel please review.
=> Cleaned up TreeSelector component to be more similar to TreeView

webpack.config.js
As @skateman talked with me, it would be good to throw error whenever there is warning in tslint, so we force people to obey rules much thoroughly. However emit file anyways so we can fix these things later on (while on `npm start`/`yarn start`), build on the other hand will fail so travis will complain about these errors as @himdel proposed.
=> When any warning happens in tslint, throw error

src/dialog-editor/services/modal/modal.html
This should solve issue with setting dynamic to true. Proiblem was, that the data was not passed to modal dialog-editor-modal-field-template.
@eclarizio @romanblanco @h-kataria
=> Add modalDat when dynamic is set to true in modal

src/styles/dialog-editor.scss
The gray background looked strange in the editor, trying white colour
Before:
After:
@dtaylor113 what you think?
=> Changed background color in the Dialog Editor

src/gtl/components/data-table/data-table.html, src/gtl/components/data-table/dataTableComponent.ts
The `hasOwnProperty` wasn't testing if the property is `null` so the `hasImage` and `hasIcon` functions always returned `true`.
=> Fixed GTL icons and images when both are present

demo/styles/demo-app.scss, demo/views/toolbar-menu/basic.html, demo/views/toolbar-menu/custom-html.html, src/styles/ui-components.scss, src/toolbar/components/toolbar-menu/toolbar-button.html, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbar-menu.html, src/toolbar/components/toolbar-menu/toolbarComponent.ts
This PR cleans up the toolbar markup and styling and adjusts the button positioning to match Patternfly.
Follow-up PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/2226
Old
New
=> Toolbar styling and markup cleanup

package.json, scripts/.build.sh, src/common/components/sortItemsComponent.spec.ts, src/common/components/sortItemsComponent.ts, src/dialog-editor/components/box/boxComponent.ts, src/dialog-editor/components/tab-list/tabListComponent.ts, src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/gtl/components/data-table/dataTableComponent.spec.ts, src/gtl/components/pagination/paginationComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarComponent.spec.ts
Coverage is right now generated from minified version of ui-components, which is not totally great. So this PR introduces new script in `package.json` which is `build-dev`, it's the same as `build` however it does not uses `-p` for `webpack` so we have normal output.
Also fixes couple of problems with build, where it threw error with some variables without type and some empty function blocks are rewritten from `function() {}` to `() => true`, which is shorter and does not produce any errors.
=> Do not use minified version of ui-components in coverage tests

demo/data/dialog-data.json, src/styles/ui-components.scss
**Pivotal tasks**:
https://www.pivotaltracker.com/story/show/150614285
https://www.pivotaltracker.com/story/show/150614221
@chalettu can you take a look on this?
=> Remove CSS rule to hide help icon in dialog fields

src/gtl/services/dataTableService.spec.ts, src/gtl/services/dataTableService.ts
This PR tries to unify variables across ui-classic and ui-components when fetching data so we can simplify retrieving rows and columns. In the end only modelName, id and pagination settings will be sent to server.
Right now it uses both old config data names and new ones, so there is no problem when merging this first.
=> Use new names for report_data

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
In the classic UI, there was an issue when using a date or date/time field where if there is not a default value set, it was passing in an undefined attribute for `.values`, and thus the ui-component was crashing trying to do `new Date(data.values)`.
This should fix that issue and just initialize the date or date/time field to the current date and time.
@chalettu Can you review?
=> Fix issue in dialog-user where values for dates were undefined

src/gtl/components/data-table/data-table.html, src/gtl/components/tile-view/tile-view.html, src/gtl/interfaces/abstractDataViewClass.ts, src/gtl/services/dataTableService.ts
This PR allows us to add additional options to report data requests. This was required by multiple people in core repo, and would allow us to easily add new options when filtering for data.
* `bindTo` property in buttons - When someone would like to use button in GTL (on rows) now he can also add `bindTo` property to such table column and bind specific object to it. So when button is clicked it can access functions related to bound object.
* `disabled` buttons - When button is rendered in table or big tile it can be disabled by property `disabled`.
Example of how to use `bindTo`
```Typescript
class SomeComponentClass {
public rows: any[];
public function onButtonClick(item) {
//do some action with item
}
public addButtonToTable() {
this.rows.each(oneRow => {
oneRow.cells = …
```
=> Enable to use disabled buttons in GTLs, add optionalData to ajax and enable bindTo for buttons in GTL

package.json, src/vendor.ts, yarn.lock
This will allow us to use ES6 features in testing (PhantomJS) and in development (IE11).
=> Add es6-shim dependency for development and testing

src/tree-view/treeViewComponent.ts
The treeview requires an element ID for the proper styling setup. Without it the styling of nodes might be ignored if you have more than one treeview on a single page. I added a dynamic ID to the component's template, however, it was necessary to delay the tree rendering until the ID is set properly.
The best way to test this is through the *Automate -> Customization -> Buttons* tree, where you can have colored icons.
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1498052
=> Don't render the treeview before the angular template is fully ready

src/common/components/sortItemsComponent.ts
Fields based on which can be sorted out no longer multiply after clicking on pagination, sort etc.
=> When headers change for pagination, clear fields so they don't multiply

src/tree-view/treeViewComponent.ts
This is a "hack" until we drop the jQuery calls from MIQ which can select nodes outside the angular's scope. It's ugly, it's not a thing we want but there's no better fix :cry: 
🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆
https://bugzilla.redhat.com/show_bug.cgi?id=1500176
=> Don't rely on the selected binding when reloading with preselect 🦆

src/dialog-editor/components/modal-field-template/check-box.html, src/dialog-editor/components/modal-field-template/date-time-control.html, src/dialog-editor/components/modal-field-template/dialog-field-association-info.html, src/dialog-editor/components/modal-field-template/dynamic.html, src/dialog-editor/components/modal-field-template/radio-button.html, src/dialog-editor/components/modal-field-template/tag-control.html, src/dialog-editor/components/modal-field-template/text-area-box.html, src/dialog-editor/components/modal-field-template/text-box.html, src/dialog-editor/services/dialogEditorService.spec.ts, src/dialog-editor/services/dialogEditorService.ts, src/dialog-editor/services/modal/modal.html, src/dialog-editor/services/modal/modalService.ts
Note that users will no longer be able to turn on "auto refresh" or "auto refresh other fields when modified" after this PR, as the dialog field associations are going to end up handling that logic. The classic UI dialog editor will still retain these options for now.
This will require [this PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/2112) from the classic UI to ignore the list of dynamic dialog fields that is going to be passed through the API, as well as [this PR](https://github.com/ManageIQ/manageiq/pull/15937) from the main repo to actually build the associations from the IDs being passed in.
https://www.pivotaltracker.com/story/show/148013513
/cc @gmcculloug, @romanblanco 
=> Add ability to edit the dialog field associations in the UI

src/tree-view/treeViewComponent.ts
`selected` & `reselect` were already optional
`onSelect` & `lazyLoad` are now :)
Cc @skateman
=> treeview - mark optional bindings optional

src/toolbar/components/toolbar-menu/toolbar-button.html, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbar-view.html, src/toolbar/components/toolbar-menu/toolbarButton.spec.ts, src/toolbar/components/toolbar-menu/toolbarList.sample.json, src/toolbar/components/toolbar-menu/toolbarListComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarViewComponent.spec.ts, src/toolbar/interfaces/toolbar.ts
Serves to replace the `url_params =~ /_div$/` (and `url_params =~ /id=LIST/`) hacks used to trigger sending a list of checked items before.
part of ManageIQ/manageiq-ui-classic#588
Cc @karelhala
=> Toolbar - add send_checked?: boolean to toolbar buttons, listitems and viewbuttons

demo/data/dialog-data-refresh.json, src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts
Previously, we had to iterate through the list of refreshable fields and determine which was next to be refreshed, then queuing up requests for each field one after another.
After this change, if the dialog field has responders on it, it will use those instead of relying on the auto refresh logic. This is because right now in the ops UI, dialog fields can be edited either in the old editor or the new editor, and field responders can only be set in the new editor.
https://www.pivotaltracker.com/story/show/149808445
/cc @gmcculloug
@chalettu Can you review, please?
=> Introduce targeted auto refresh logic alongside cascading logic

src/fonticon-picker/components/fonticon-picker/fonticon-modal.html, src/fonticon-picker/components/fonticon-picker/fonticonPickerComponent.ts
According to the BZ below, the `Apply` button needs to be disabled when:
* There is no fonticon selected in the modal
* There are no changes against the previous selection
https://bugzilla.redhat.com/show_bug.cgi?id=1501247
=> Disable the Apply button in the fonticon picker when necessary

demo/data/data-table.json, src/gtl/components/data-table/data-table.html, src/gtl/components/data-table/dataTableComponent.spec.ts, src/gtl/components/data-table/dataTableComponent.ts
For now we have two types of node images in GTL list views: fonticons and fileicons. The priority is always fonticons first, however, sometimes we have custom uploaded pictures and they should be favored even over fonticons.
My solution is to introduce the new picture type with the highest priority. This will be sent for some nodes only and it should not affect the behavior of screens where there are no custom uploaded pictures. I also dropped the `hasImage` and `hasIcon` functions and introduced `getNodeIconType` that returns with the node image type that should be displayed. Tests and examples have been also adjusted.
There is also a [ui-classic PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/2573) that updates `report_data` to provide the `picture` attribute when necessary but …
=> Allow three types of nodeIcons in the order: picture > icon > image

src/dialog-editor/components/modal-field/field.html
A mistake caused by rewriting modal. After this change, the `name` field should be available again.
=> Removed obsolete ng-if that made the name field disappear

src/dialog-editor/components/modal/modalComponent.ts
This has a change that is needed in order to be able to edit the field associations in the editor properly. UI-classic PR that contains the necessary code: https://github.com/ManageIQ/manageiq-ui-classic/pull/2067/files#diff-7f0e7be06cf6602a0477d7092bce6ad2R28
https://www.pivotaltracker.com/story/show/149808445
@romanblanco Can you take a look at this and the corresponding part in ui-classic to make sure I'm not missing anything?
@chriskacerguis This will need to be merged around the same time as the ui-classic PR otherwise I'd expect some strange behavior.
@miq-bot assign @chriskacerguis
=> Remove name -> id translation as it is done in ui-classic now

src/gtl/components/pagination/pagination.html, src/gtl/components/pagination/paginationComponent.spec.ts, src/gtl/components/pagination/paginationComponent.ts
Whenever pagination changes (sort order, sort by, number of items etc.) select all stays selected no matter what. With this PR when performing such actions select all will be deselected.
https://bugzilla.redhat.com/show_bug.cgi?id=1501196
=> When settings of pagination changes, set isChecked to false

demo/controllers/availableComponentsController.ts, demo/controllers/dataTableController.ts, demo/controllers/dialogEditorController.ts, demo/controllers/dialogUserController.ts, demo/controllers/fonticonPickerController.ts, demo/controllers/siteSwitcherController.ts, demo/controllers/toolbarMenuController.ts, demo/controllers/treeSelectorController.ts, demo/controllers/treeViewController.ts, demo/services/availableComponentBuilder.ts, demo/services/availableComponentsService.ts, src/common/components/sortItemsComponent.ts, src/dialog-editor/components/box/boxComponent.ts, src/dialog-editor/components/tab-list/tabListComponent.ts, tsconfig.json
To register new group you will have to add new item with name, location, title and empty array of components. When registering available component use custom decorator above some class to register it:
```Typescript
@ComponentDemo({
name: 'tree-view-new',
title: 'TreView',
template: require('./../views/tree-view/basic.html'),
controller: 'demoTreeView as vm'
})
export default class TreeViewController {
//Demo treeView controller implementation
}
```
If you need more components registered under same controller use `AvailableCmp` multiple times as seen at [demo/controllers/dataTableController.ts](https://github.com/ManageIQ/ui-components/pull/127/files#diff-5884d947210a1d2824f3a7a10e833088)
```Typescript
@ComponentDemo({
name: 'small',
title: 'Small tile',
template: …
```
=> Add available component builder so we can use it much easilly

package.json, src/vendor.ts
Array.includes is still not supported by IE10/11 (and PhantomJS)
That breaks specs in #209.
Adding es7-shim too.
Cc @romanblanco
=> Add es7-shim

src/dialog-user/components/dialog-user/dialogField.html
I think this was an oversight by @chalettu, we still need invisible fields to be there in the data, but the visible flag is just so that they aren't actually shown to the end user. They still need to be rendered in HTML so that their values are stored in the data structure and sent to the API when the user submits the form.
@mkanoor This should fix the issue you found with visible fields.
@miq-bot assign @chriskacerguis
=> Change ng-if to ng-show for visibility dialogField property

src/dialog-editor/components/field/fieldComponent.ts
When removing dialog editor field ids are not recalculated so after clicking on edit field inside dialog group either error (when penultimate was removed) or wrong modal is shown (with wrong data).
=> When field is removed from dialog editor refresh positions of field elements

src/dialog-editor/components/modal-field-template/drop-down-list.html
The switch should be visible for dynamic dropdown field, and only when the “show refresh button” checkbox is checked:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1514584
@karelhala @eclarizio
=> Added 'Load values on init' option for dynamic dropdown field

src/dialog-user/services/dialogData.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518971
Instead of testing for value of `validator_type`, test for presence of the attribute that actually has the validation rules.
/cc @chalettu
=> Test for presence of 'validator_rule' instead of testing 'validator_type'

src/dialog-user/components/dialog-user/dialog.html, src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.ts, src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts, src/dialog-user/interfaces/abstractDialogFieldClass.ts
The refresh button wasn't really doing anything before, because it was trying to call a `changesHappened` method which actually didn't exist, but even if it did `changesHappened` was the incorrect thing to call. WIP for now as I need to add some specs and address a strange issue I found when I tried to refactor and it ended up breaking.
https://bugzilla.redhat.com/show_bug.cgi?id=1513162
=> Ensure refresh button works and calls a single refresh for dialog fields

src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts, src/dialog-editor/components/modal/modalComponent.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518506
The value edited by bootstrap switch was changed in different scope, so the value of `treeSelectorIncludeDomain` in the original scope was still set on `false`.
Making the both-ways binding should fix the issue.
cc/ @h-kataria
=> Allow the attribute to be edited in the original scope

src/dialog-editor/services/dialogEditorService.spec.ts, src/dialog-editor/services/dialogEditorService.ts
This got changed back in https://github.com/ManageIQ/ui-components/pull/223, but it makes it so that when you try to edit anything other than drop down or radio button fields (the ones that use objects for their values), it attempts to call `.filter` on a string and ends up blowing up silently in JS with you unable to edit your fields.
@romanblanco @martinpovolny please review
=> Fix assumption that all field.values are objects

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1514196
=> BZ#1514196 - Dynamic checkboxes in Dialog component

src/dialog-editor/components/modal-field-template/check-box.html, src/dialog-editor/components/modal-field-template/date-time-control.html, src/dialog-editor/components/modal-field-template/drop-down-list.html, src/dialog-editor/components/modal-field-template/fields-to-refresh.html, src/dialog-editor/components/modal-field-template/radio-button.html, src/dialog-editor/components/modal-field-template/tag-control.html, src/dialog-editor/components/modal-field-template/text-area-box.html, src/dialog-editor/components/modal-field-template/text-box.html
The problem is that when creating or editing dialogs, if you add a new field, the field is not saved before the associations are created, and so there is no id to send up. Therefore we have to send up the name and have the backend handle the association creation by name instead.
This will need to be combined with [this main repo PR](https://github.com/ManageIQ/manageiq/pull/16753) in order to fully fix the bug.
https://bugzilla.redhat.com/show_bug.cgi?id=1518942
@miq-bot add_label gaprindashvili/yes, bug
@romanblanco @himdel Please review
=> Use '.name' instead of '.id' for refresh field list

src/dialog-editor/components/toolbox/toolboxComponent.ts, src/dialog-editor/services/dialogValidationService.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507751
Adding another validation rule to make sure the dialog with dropdown or radio button without values is not sent.
___
One more thing here - I'd expect the same validation to be in the backend, even though normally the user shouldn't be able to send such dialog.
I've checked with @d-m-u and currently, we are setting `[[nil, "<None>"]]` as the initial value ([here](https://github.com/ManageIQ/manageiq/blob/master/app/models/dialog_field_drop_down_list.rb#L16)), and that will stay, if the dialog is submitted with no values.
Is this OK? Or should this be handled differently?
/cc @eclarizio @d-m-u
=> Validate presence of values for Dropdown list and Radio button

src/dialog-editor/components/box/boxComponent.ts
Drag&Drop of a box was causing an error of calling method for `undefined`
=> Update field name only when the field (not a box) is dropped

src/dialog-editor/services/dialogValidationService.ts
Fixing a bug introduced by https://github.com/ManageIQ/ui-components/pull/231.
We actually want to check if the values are empty in case the field is Dropdown or Radio button.
=> Corrected validation expression

src/dialog-editor/services/dialogValidationService.ts
It was not possible to save a dialog that didn't have values, because it was dynamic.
This PR fixes the issue.
=> Test values only for non-dynamic dropdown and radio button

src/dialog-editor/components/modal/modalComponent.ts, src/dialog-editor/services/dialogEditorService.spec.ts, src/dialog-editor/services/dialogEditorService.ts
Create a new dialog, add a dynamic field, add a non-dynamic field and edit that one.
In the list of fields to refresh, the first field should be visible.
Without this, it's not, because the freshly created field has no id, and passing undefined to `getDynamicFields` would cause it to skip all the fields with undefined id.
..updated to skip undefined
..and changed to use `name` instead of `id` to keep in line with https://github.com/ManageIQ/ui-components/pull/228
(Two-part fix, this PR should go first, so that the [ui-classic PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/3302) can be tested :).)
Cc @romanblanco @eclarizio 
https://bugzilla.redhat.com/show_bug.cgi?id=1536528
=> DialogEditor - getDynamicFields - don't skip fields without id

demo/views/dialog/editor.html
Theoretically if someone would want to replace an old dialog with dialogPlayer + JSON, there is no easy way to create the JSON. This one-liner is to fix this problem!
@karelhala @himdel @romanblanco
=> Display the dialog's JSON in the dialog editor demo page

src/dialog-editor/components/field/field.html, src/dialog-editor/components/modal-field-template/radio-button.html
There was a bug in the way that the default value was being sent to the API in that it was trying to send the full value (so for example ["1", "one"] instead of just "1"). The way that the `ng-checked` property works was also not actually as intended, all that needs to be done is to ensure that `ng-value` and the `ng-model` are equivalent and angular will handle selecting the correct value. The `ng-checked` property is for if you want to send up different data than what is contained in the `ng-value` property. This fixed the actual correct default value showing up in the editor, as seen in the below screenshots:
The other issue was that the "Nothing selected" value was always selected from the dropdown list when editing the default value for radio buttons, and this has been fixed to show …
=> Ensure default value for radio button is rendered properly

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/3371
This should fix the issue with the timepicker not being visible in the service UI, and also fixes another issue I found with the checkbox not displaying the correct default value on the initial load of ordering the service.
https://bugzilla.redhat.com/show_bug.cgi?id=1540273
=> Fix for different behavior of items in regards to default values

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.ts
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1539862
=> BZ#1539862 - Created multiselect dialog field type

src/dialog-editor/components/modal-field-template/radio-button.html, src/dialog-editor/components/toolbox/toolboxComponent.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531571
The initial values need to be a string, so the comparison and thus displaying `default_value` works correctly.
=> Corrected type for initial values

src/dialog-editor/components/abstractModal.ts, src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts, src/dialog-editor/components/modal-field-template/tag-control.html, src/dialog-editor/components/modal-field/field.html, src/dialog-editor/components/modal/modalComponent.spec.ts, src/dialog-editor/components/modal/modalComponent.ts
Create a function setupCategoryOptions to be called on ng-change
Gigantic Thank you to @eclarizio for all his help!
https://bugzilla.redhat.com/show_bug.cgi?id=1542590
=> Set ng-change for tag control options

demo/controllers/dialogEditorController.ts, demo/views/dialog/editor.html
Some copy-pasted code from ui-classic's `dialog_editor_controller.js` and `editor.html` that will make the modals work in the demo.
=> Add missing code to make the dialog editor working in the demo

ci/bower-dev.sh
When releasing new version to bower it does not install dependencies which causes error, this PR fixes such issue and before releasing new version to bower it installs required dependencies.
=> Update Bower dev CI to install dependencies before releasing

src/vendor.ts, webpack.config.js, webpack.vendor.config.js
@karelhala asked @karelhala gets it, we want this as a dependency in ui-classic.
=> Mark numeral.js as an external dependency provided by ui-classic

src/vendor.ts
When adding selectbox in demo page for dialog editor, there was an error with missing selectpicker. This was caused due to missing dependency in vendors.
**none**
=> Add bootstrap-select to vendor dependencies

demo/controllers/dialogEditorController.ts, demo/views/dialog/editor.html, src/dialog-editor/components/dialog-editor/dialog-editor.html, src/dialog-editor/components/dialog-editor/dialogEditorComponent.ts, src/dialog-editor/components/dialog-editor/index.ts, src/dialog-editor/components/index.ts
Wrapping the whole dialog editor into a single component. Some bindings have been moved into this component, but in the future they should be moved deeper in the codebase. I renamed the `onSelect` function to `treeSelectorSelect` as this name is more descriptive.
For now marking it as a WIP as the textarea is missing from the demo.
@miq-bot assign @romanblanco
=> Create a top-level dialog editor component

demo/data/data-table.json, src/gtl/components/tile-view/tile-view.html
When rendering report_data tile (small/big) show quadicon instead of using HTML when possible.
=> Add quadicon into report data, small tile and big tile

demo/index.ts, demo/services/APIService.ts, demo/services/DialogEditorHttpService.ts, src/dialog-editor/components/modal/modalComponent.spec.ts, src/dialog-editor/components/modal/modalComponent.ts
We do not want to depend on any specific API in this repo, the preferred way is to use a service that does these things externally.
Original idea: https://github.com/ManageIQ/manageiq-ui-classic/pull/3414 and https://github.com/ManageIQ/ui-components/issues/219
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/3426
@miq-bot assign @romanblanco
=> Use the external DialogEditorHttpService for retrieving categories

src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
@miq-bot add_label gaprindashvili/yes 
This PR also addresses an issue where "None" option should default to staying at the top of a dropdown list of options.
Fix for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1531677
=> Updated support for sorting of drop downs

karma.conf.js, webpack.config.js
When running tests new window is opened in browser which is then unresposnive, because server terminates itself once tests are done. This PR fixes such issue by changeing webpack config to allow passing variables
=> Do not open browser when running tests

src/dialog-user/components/dialog-user/dialogField.html
When we switched over to the new dialog-user component, we forgot to include the live-search ability that was on the older bootstrap drop downs. This will put those back into place, and adds the `data-tokens` property to the options so for example if someone has a drop down that submits the value of `3` but the option for selecting is `"Three"`, then they can search by typing either `3` or `three`.
See screenshots:
https://bugzilla.redhat.com/show_bug.cgi?id=1553347
=> Add ability to live-search dialog drop down fields

src/dialog-user/services/dialogData.ts
The main problem here is that we need to use `ng-repeat` to list out the options for a select. This, however, only supports strings for the value field, so when the drop down has a `data_type` of integer, we were coercing the default value into an integer, which would cause a mismatch and nothing would be selected. I'm not exactly sure why the weird double select was happening with this, but removing the integer coercion fixes the issue.
Here's what it looks like before (note that nothing is selected by default because it's trying to match `2` with `'2'`):
Here's what it looks like after:
I've made sure that on the back end, when we actually do submit the dialog, that the request gets the correct type. It is being coerced on the back end via …
=> Fix for drop-down selection on dialogs while ordering service catalog having to select an item twice

src/dialog-editor/components/box/box.html, src/styles/dialog-editor-boxes.scss
Fixing a CSS style, so the values in the dropdown are visible.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1557508
Before:
After:
/cc @dtaylor113 
Thanks for the help, @Hyperkid123
=> Style correction for dialog dropdowns

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
@AllenBW can probably give a bit more context on this, but basically if you do not set a default value for an integer based drop down, it will default to `null`. Well, this gets converted into "NaN", which does not match `null` as a default value and therefore doesn't end up actually selecting the first value which should be `"<None>"` but instead just shows "Nothing Selected".
Before, the string drop downs work fine with no default, and the integer ones have the "Nothing Selected" text:
After, all of them behave the same:
https://bugzilla.redhat.com/show_bug.cgi?id=1557482
@chalettu Can you please review?
I'm not tracking the BZ quite as closely as @AllenBW, so Allen, if I got the wrong labels please correct me 👍 
@miq-bot add_label gaprindashvili/yes, bug, …
=> Ensure 'null' default values do not get coerced into 'NaN' for integer type drop downs

src/styles/ui-components.scss
This PR adjusts the size of the quad icons from 80px to 78px.
Old
New
=> Adjust size of quad icons

src/dialog-user/components/dialog-user/dialogField.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1559159
The problem is the default options `<Choose>` and `<None>` had no id, and so the `default_value` remained unset and so an empty option field was created. (https://stackoverflow.com/a/12654812)
```ruby
[{:id=>nil, :name=>"<Choose>", :description=>"<Choose>"},
{:id=>10000000000035, :name=>"silver", :description=>"Silver"},
{:id=>10000000000036, :name=>"gold", :description=>"Gold"},
{:id=>10000000000037, :name=>"platinum", :description=>"Platinum"}],
```
In the fix I'm setting a value of the default options to 0, and setting them as default.
=> Setting the default_value for TagControl dialog field

src/gtl/components/data-table/data-table.html, src/gtl/components/data-table/dataTableComponent.spec.ts, src/gtl/components/pagination/pagination.html, src/gtl/components/pagination/paginationComponent.spec.ts, src/gtl/components/pagination/paginationComponent.ts, src/gtl/components/tile-view/tile-view.html, src/gtl/components/tile-view/tileViewComponent.spec.ts, src/gtl/interfaces/abstractDataViewClass.ts
When user is in GTL view screen and no checkboxes are available select all is still present, this is wrong. This PR fixes such issue by adding new method in `src/gtl/interfaces/abstractDataViewClass.ts` and setting one way data bounded `hasCheckboxes` in `src/gtl/components/pagination/paginationComponent.ts`
This PR is multiple PR work, it needs to be merged and new version released before merging TODO ui-classic.
=> When no checkboxes are visible in GTL hide select all

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Before, we were using lodash's `_.isEmpty` method to determine if something was selected or not, but `_.isEmpty` does not behave the Ruby version we know and love. It only determines if an object is empty, not a variable. So, the problem was that the tag control select was passing in a category id, which was a number, and `_.isEmpty(1234)` returns true. Therefore validation was failing 😢.
This changes the logic so that when a single value is to be selected, we check to see if it's a number. If it's 0 (which is the "choose" value), then we still need to select something, otherwise we should be ok. If it somehow gets set to null, we should still also be failing validation.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567108
@miq-bot add_label gaprindashvili/yes, bug
@miq-bot assign …
=> Fix for Catalog Item with Tag Control element cannot be ordered

src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts
The change is very simple but I broke it out into a function refactor as well since it becomes much easier to test this way.
The effective change is:
```
-    this.dialogValues[field] = data.values;
+    this.dialogValues[field] = data.default_value;
```
In the code below, it's line 207 that gets changed for line 222
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568440
@miq-bot add_label gaprindashvili/yes, bug
@chalettu Can you review please?
=> Fix for default value containing all values of a list instead of single value

src/styles/ui-components.scss
This PR corrects an issue where text within the quad icons was underlined on hover.
Old
New
=> Remove underlined text from quads

src/vendor.ts
boostrap-select 1.13 came out, with a [change](https://github.com/snapappointments/bootstrap-select/commit/0029b3dbb2d5218c4ee7872179019f742ab674bd) that requires bootstrap to be included first, before bootstrap-select
This causes travis to fail with
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
TypeError: undefined is not an object (evaluating '$.fn.dropdown.Constructor')
at dist/js/vendor.js:72739
```
adding a bootstrap import.
=> Fix travis failing on $.fn.dropdown.Constructor undefined from new bootstrap-select

src/dialog-user/components/dialog-user/dialogField.html
The PR adds a data-container target of "body" to bootstrap selects it prevent dropdowns from being cut off.
https://bugzilla.redhat.com/show_bug.cgi?id=1568486
Old
New
=> fix cutoff dropdowns

src/common/filters/abbrNumberFilter.spec.ts, src/common/filters/adjustColorFilter.spec.ts, src/common/filters/adjustColorFilter.ts, src/common/filters/index.ts, src/toolbar/components/toolbar-menu/toolbar-button.html, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbar-view.html, src/toolbar/index.ts
If a custom color is defined for a toolbar button's icon, the `.disabled` property is not being respected on it. I created a new `adjustColor` filter that has an extra boolean argument. If the boolean is true or the input is unsed, the filter just returns the input, otherwise it converts the hex color into an `rgba(x, y, z, 0.5)` value.
**Before:**
**After:**
@miq-bot add_reviewer @epwinchell 
@miq-bot assign @karelhala 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501114
=>  Adjust the opacity of custom colored icons when they are disabled

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
When a checkbox has a `default_value` set, it was preferring to use that instead of the value coming back from a dynamic method call. This could happen when importing a dialog with a checkbox field and a `default_value` set in the yaml, or when perhaps converting an originally static checkbox field into a dynamic one.
https://bugzilla.redhat.com/show_bug.cgi?id=1570152
/cc @chalettu Please review
@miq-bot add_label bug, blocker, gaprindashvili/yes
=> Fix for dynamic checkbox not updating properly

src/dialog-editor/components/modal/modalComponent.spec.ts, src/dialog-editor/components/modal/modalComponent.ts
Certain categories have different names than their description, and so sometimes it was failing when trying to choose them to use. This fixes the issue with [this PR from the classic UI](https://github.com/ManageIQ/manageiq-ui-classic/pull/3865) so that we get the correct name from the API in the first place.
The Classic UI PR needs to be merged first.
https://bugzilla.redhat.com/show_bug.cgi?id=1570613
/cc @gmcculloug @d-m-u 
@miq-bot assign @himdel  
@miq-bot add_label gaprindashvili/yes, bug
=> Use the name of the category that comes from the API as category_name

src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts
Ok, so it turns out the fix for https://github.com/ManageIQ/ui-components/pull/279 was a bug only for sorted items, because sorted items use a default value to show what is selected. However, for something like a textbox/checkbox/date element, "values" are used. So, this will use default_value for sorted items but values for non-sorted items.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568440
@chalettu One more review, please? 😄 
=> Fix for default value being set incorrectly for non 'DialogFieldSortedItem' field types

src/gtl/services/dataTableService.ts
When switching pages and order of sort is set to DESC it's forgotten and used ASC. This PR fixes such issue by sending `is_ascending` in params, undefined value is mapped to false.
https://bugzilla.redhat.com/show_bug.cgi?id=1481840
=> Send ascending true or false, if undefined set to false for report data

src/styles/toolbar.scss, src/styles/ui-components.scss, src/toolbar/components/toolbar-menu/index.ts, src/toolbar/components/toolbar-menu/toolbar-item-click.html, src/toolbar/components/toolbar-menu/toolbar-kebab.html, src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbar-menu.html, src/toolbar/components/toolbar-menu/toolbarClickDirective.spec.ts, src/toolbar/components/toolbar-menu/toolbarClickDirective.ts, src/toolbar/components/toolbar-menu/toolbarComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarComponent.ts, src/toolbar/components/toolbar-menu/toolbarKebabComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarKebabComponent.ts, src/toolbar/interfaces/toolbarType.ts
When on screen with toolbar and many custom buttons These buttons should be combined together into kebab menu. If such button is group of buttons this feature has to be consistent and hovering above such button in kebab new drop down will be visible (preferably drop right).
This PR implements such issue by introducing one new component and one directive.
* New directive is for MiQ action buttons so we don't have to repeat same settings all over again.
* New component implements two level dropdown menu with kebab icon and whenever more than **3** custom buttons are present in toolbar they will be squashed together into kebab menu.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1552064
=> Create new kebab component and toolbar click to merge toolbar custom buttons together

src/dialog-user/components/dialog-user/dialogField.html
This PR is a follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/3668 and addresses the following requests:
-  correctly applies form-horizontal class for label positioning
-  decrease size of label column 
-  increase size of text area
-  decrease size of dropdowns
-  move refresh button below text area
https://bugzilla.redhat.com/show_bug.cgi?id=1553697
Old (Classic UI)
New (Classic UI)
Old (Classic UI)
New (Classic UI)
Old (Service UI)
New (Service UI)
=> Fix Dialog Editor styling issues

application-settings.js, karma.conf.js, src/dialog-user/components/dialog-user/dialogField.html, src/index.ts, src/miq-select/index.ts, src/miq-select/miqSelect.js, src/miq-select/miqSelect.spec.js
Tagging @himdel for some assistance on this one.
~~I basically can't seem to get the template to actually convert the `<select>` tags to the way bootstrap does it with the `<ul>` structure. If I'm in the classic UI and I manually call something like `$('select').selectpicker()`, it works, but the directive should be doing that.~~
~~You can even see in the specs, the spec on line 29 that is doing the expect on the `select.text()` isn't the one that fails, it's failing trying to find the length of the "bootstrap" select elements it's supposed to generate, and then failing on all the other specs assessing the other properties of those elements.~~
The issue is kind of a corner case, but the reason for this change is mainly due to the fact that we are using the `data-live-search` feature for …
=> Use new 'miq-select' directive instead of patternfly

demo/controllers/quadiconController.ts, demo/styles/demo-app.scss, demo/views/quadicon/basic.html, src/quadicon/components/quaditem/quaditem.html, src/quadicon/components/quaditem/quaditemComponent.ts, src/styles/ui-components.scss
Currently we have 20 PNG images for displaying pie charts, so I dynamically generated 20 CSS classes that mimic the behavior of the PNGs. The solution is intended to be universal, i.e. to use them not just in quadicons, so the full styling will go into `ui-classic`.
@miq-bot add_reviewer @himdel 
@miq-bot add_reviewer @karelhala 
@miq-bot add_reviewer @epwinchell
=> Add support for displaying simple CSS piecharts in quadicons

src/dialog-editor/components/modal/modalComponent.ts
If the dialog is saved with a dynamic dropdown, there are no values in it, therefore `modalData.values` is `null` and makes it impossible to add any entries.
The fix tests if the `modalData.values` is `null`, and if so, it initializes it with empty array
Fixes: https://github.com/ManageIQ/ui-components/issues/301
/cc @d-m-u
=> Make possible to add values after dropdown is changed to static

src/dialog-editor/components/modal-field-template/check-box.html, src/dialog-editor/components/modal-field-template/text-area-box.html, src/dialog-editor/components/modal-field-template/text-box.html
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1576107
Basically the same change as in https://github.com/ManageIQ/ui-components/pull/296.
To test this, the dialog element must be dynamic and "Show Refresh Button" option must be turned on.
=> Added missing checkbox to allow load dynamic dialog values on init

src/gtl/components/tile-view/tile-view.html, src/gtl/interfaces/abstractDataViewClass.ts, src/gtl/interfaces/dataTable.ts
When in Grid/Tile view and no records are available gray stripe is visible on above message "No records found"
=> Do not display cardview if no data available

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
The dialog-user component was ignoring the fact that the `sort_by` option could be set to none, so it was always either sorting by `value` or `description`, instead of simply leaving the values as they come in. This will need to be combined with [this PR from the main repo](https://github.com/ManageIQ/manageiq/pull/17625) to fully fix the BZ reported, which is also happening during editing of the dialog.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1593874
@d-m-u Please review
/cc @tinaafitz
=> Do not sort dropdowns that have sort_by set to 'none'

src/dialog-user/components/dialog-user/dialogField.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1578986
behaviour for `nil` attributes is changed in https://github.com/ManageIQ/manageiq-api/pull/253
=> Test that 'id' attribute is missing

src/gtl/components/data-table/data-table.html, src/gtl/components/data-table/dataTableComponent.spec.ts, src/gtl/components/data-table/dataTableComponent.ts
The picture attribute is no longer necessary as I'm reprioritizing the `fileicon` over the `fonticon` in GTLs.
Classic UI PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/4198
@miq-bot add_reviewer @epwinchell 
@miq-bot add_reviewer @karelhala 
@miq-bot add_reviewer @martinpovolny 
@miq-bot add_labels gaprindashvili/no, GTLs, graphics
=> Remove the picture nodeIcon and prioritize the rest as image > icon

src/dialog-editor/components/modal-field-template/drop-down-list.html, src/dialog-editor/components/modal-field-template/modalFieldTemplateComponent.ts
Corrections after changes in https://github.com/ManageIQ/ui-components/pull/310
- switched labels for description / value
- update select box after changing the values order manually
This change goes to `gaprindashvili` branch.
I'll add a new PR with the changes done in #310 together with some [specs](https://github.com/ManageIQ/ui-components/pull/310#issuecomment-400359683) to `master`.
@himdel @ZitaNemeckova
=> [GAPRINDASHVILI] Corrected description / values for dropdown list

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/components/dialog-user/dialogField.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Date & time picker was trying to use one model for both input fields, so when the date would change, the time would basically get reset, and when the time changed, the date would get reset so the user could never actually pick the time and date they wanted to pick.
This PR separates the date field and the time field into separate models but joins them back up when changes are made so that the correct value is sent to the API when the user presses 'submit'.
Ultimately, I think we should probably look into a whole "datetimepicker" solution, such as https://www.npmjs.com/package/angular-ui-bootstrap-datetimepicker.
Interestingly enough, patternfly *does* have a datetimepicker that I found (https://www.patternfly.org/pattern-library/forms-and-controls/date-and-time/), however, I don't think …
=> Use separate 'changesHappened' update call for datetimepicker

locale/ui-components.pot, locale/zanata.xml, package.json, scripts/validate-gettext-catalog.js, src/dialog-editor/components/box/box.html
What this PR does:
* use `angular-gettext-cli` to extract strings from javascript sources & html markup
* remove extraneous `translate` directive
* add `locale/` subdirectory with `ui-components.pot` catalog
* add gettext catalog validation
* add `zanata.xml`
=> i18n string extraction & friends

src/dialog-user/components/dialog-user/dialogField.html
This PR fixes a problem where the Refresh button becomes hidden when the text area is expanded.
It also:
* adds missing "btn-default" class
* changes the "Refresh" text to a font icon; adds tooltips
* prevents horizontal expansion of textarea.
This PR is a follow-up to: https://github.com/ManageIQ/ui-components/pull/293
https://bugzilla.redhat.com/show_bug.cgi?id=1602048
Old
New
=> fix refresh button placement in dialog show screen

src/dialog-user/services/dialogData.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1600007
replacing `parseInt()` with `parseFloat()` to allow to parse a string with a floating point number
=> Allow to parse a string with a floating point number

demo/controllers/quadiconController.ts, src/common/filters/abbrNumberFilter.ts
In some cases it is possible that the number abbreviation filter returns 6 characters, which is an unwanted behavior and breaks the styling of quadicons. For example `112081` returns with `112.1K`. The solution is to drop the decimal point and the number afterwards.
@miq-bot add_reviewer @epwinchell 
@miq-bot add_label bug, gaprindashvili/no
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1613355
=> Fix the number abbreviation in quadicons when hitting 6 characters

ci/bower-dev.sh
since ManageIQ/ui-components#335, the bower-dev branch didn't work because there was an extra change in locale/ after running the other tests
adding -e so that we can actually see these failures
and cleaning locale/ so that we can checkout the right branch
=> ci/bower-dev .. use -e, reset locale/ first

src/dialog-user/components/dialog-user/dialogField.ts
This adds an additional step to initialization when the field type is `DialogFieldDateTimeControl` since trying to submit the "default" for this resulted in submitting the time of the epoch even though the UI shows the current date/time.
https://bugzilla.redhat.com/show_bug.cgi?id=1583177
@miq-bot add_reviewer @himdel, @chalettu
=> Ensure DialogFieldDateTimeControl fields are properly initialized

src/toolbar/components/toolbar-menu/toolbarComponent.ts
in ui-classic, go to CI > Dashboard
You'll see:
```
angular.self-f52e962…a54.js?body=1:14962 TypeError: Cannot read property 'includes' of undefined
at toolbarComponent.ts:154
at Array.filter (<anonymous>)
at toolbarComponent.ts:154
at baseFindIndex (lodash.js:802)
at Function.findLastIndex (lodash.js:7308)
at e.collapseButtons (toolbarComponent.ts:154)
at e.$onChanges (ui-components.js:4660)
at angular.self-f52e962…a54.js?body=1:10023
at forEach (angular.self-f52e962…27a54.js?body=1:427)
at nodeLinkFn (angular.self-f52e962…a54.js?body=1:10019)
```
that's because the logic introduced in https://github.com/ManageIQ/ui-components/pull/281 to modify custom buttons fails when that button doesn't have an id
the button this is failing on:
```
{
name: "custom",
args: {
partial: …
```
=> toolbar - fix includes of undefined for custom buttons

src/dialog-user/components/dialog-user/dialogField.ts
this is a remnant from before [miq-select](https://github.com/ManageIQ/ui-components/pull/295), when we had a ng-if on patternflyVersion to determine whether to use pf-select of pf-bootstrap-select
now this is dead, removing
(also, https://github.com/ManageIQ/manageiq-ui-service/pull/1472)
=> dialogField - Remove patternflyVersion

src/dialog-editor/components/field/field.html, src/dialog-editor/components/modal-field-template/drop-down-list.html, src/dialog-editor/components/modal-field-template/fields-to-refresh.html, src/dialog-editor/components/modal-field-template/radio-button.html, src/dialog-editor/components/modal-field-template/tag-control.html, src/dialog-editor/components/modal-field-template/text-box.html, src/dialog-editor/index.ts
If we want to move to angular-patternfly v4, this is necessary and according to @himdel the safest solution that can even be backported if needed.
=> Convert all pf-select directives to miq-select

src/dialog-editor/components/abstractModal.ts, src/dialog-editor/components/box/box.html, src/dialog-editor/components/modal-field/field.html, src/dialog-editor/components/modal/modalComponent.ts
https://bugzilla.redhat.com/show_bug.cgi?id=1614436
Removing field changed from dynamic to static from the list of responders for each associated field.
Steps to reproduce:
=> Update dynamic fields responders after change

src/dialog-editor/components/modal-field-template/text-area-box.html, src/dialog-editor/components/modal-field-template/text-box.html, src/dialog-editor/components/toolbox/toolboxComponent.ts
The `validator_rule` is being set only if `validation_type` is set.
https://github.com/ManageIQ/manageiq/blob/328f68895668be400989faff1ebbf98fb8620b49/app/models/dialog_field_text_box.rb#L49
`validation_type` is not getting set by default, this PR fixes it.
=> Set 'validator_type' correctly in Dialog Editor

src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbarListComponent.ts
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1633727
=> Disable toolbar dropdown if no item in the group is enabled.

src/dialog-editor/components/modal/modalComponent.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649527
We need to find by `id` with the value of `this.modalData.options.category_id` and the 2nd arg is supposed to be an object: https://lodash.com/docs/4.17.11#find
=> Fix lodash "find" call in currentCategoryEntries.

.travis.yml
Update `nodejs` version that should be used by Travis from `6` to `8`.
Error:
```
$ yarn global add typings webpack karma typescript
yarn global v1.3.2
[1/4] Resolving packages...
warning typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
error karma@4.0.0: The engine "node" is incompatible with this module. Expected version ">= 8".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for …
```
=> Update nodejs version that should be used by Travis

.travis.yml, scripts/travis.sh
travis just runs the script,
but if the script doesn't fail,
travis is green.
The script looks like it would never fail before this (same problem in https://github.com/ManageIQ/ui-components/pull/20)
=> Make travis fail again

src/dialog-user/components/dialog-user/dialogField.spec.ts
Fixes..
```
Dialog field test #dateTimeFieldChanged calls onUpdate with the correct full date FAILED
TypeError: undefined is not an object (evaluating 'this.dialogField.options.show_past_dates') (line 9)
setMinDate@dist/js/ui-components.js:9:120490
$onInit@dist/js/ui-components.js:9:116953
src/dialog-user/components/dialog-user/dialogField.spec.ts:189:35
WorkFn@node_modules/angular-mocks/angular-mocks.js:3130:26
src/dialog-user/components/dialog-user/dialogField.spec.ts:187:32
inject@node_modules/angular-mocks/angular-mocks.js:3093:34
src/dialog-user/components/dialog-user/dialogField.spec.ts:187:32
```
the spec comes from https://github.com/ManageIQ/ui-components/pull/317,
`setMinDate` logic comes from https://github.com/ManageIQ/ui-components/pull/355
=> Fix failing spec - missing mock data

package.json
Since yarn run start opens the demo,
and the demo needs the vendor build to have happened,
we may as well run the vendor build during `yarn run start` :).
*And* `yarn run test` because tests also depend on vendor being present.
=> build vendor before yarn run start & test

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/components/dialog-user/dialogField.ts, src/dialog-user/services/dialogData.ts
Current state:
* `dialogData.setupField` gets called from `dialogField` on external changes
* `dialogData.setupField` calls `dialogData.setDefaultValue` to set the field's `default_value` field
But in addition to that,
* `dialogField` also calls `dialogField.setDefaultValue` on in `$onInit`, meaning it only happens once - to set an initial value for tags (comes from https://github.com/ManageIQ/ui-components/pull/276)
* and the dropdown template has a `ng-init` on the select element, which calls `convertValuesToArray`, but only once, because `ng-init` (comes from https://github.com/ManageIQ/ui-components/pull/250)
So, this PR moves the second set of bullet points to `dialogData.setDefaultValue`, to make sure every piece of code dealing with default_values gets called in all the …
=> dialogField - move logic for setting default_value to one place

package.json, src/dialog-user/components/dialog-user/dialogField.ts
Fixes `undefined is not an object (evaluating 'this.$newElement[0].parentNode.classList.contains')` by making sure we don't use too new a version of bootstrap-select. (ui-classic is using `@pf3/select` which is a fork of the 1.12 branch of bootstrap-select)
And just because it still fails with that, this also removes a useless `_.isObject` which narrows the type of `this.validation` from `any` to `object`, causing errors.
=> Fix travis - restrict bootstrap-select to ~1.12

src/common/components/sortItemsComponent.spec.ts, src/dialog-editor/services/dialogValidationService.spec.ts, src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/services/dialogData.spec.ts, src/gtl/components/data-table/dataTableComponent.spec.ts, src/gtl/components/pagination/paginationComponent.spec.ts, src/toolbar/components/toolbar-menu/toolbarClickDirective.spec.ts, src/toolbar/components/toolbar-menu/toolbarKebabComponent.spec.ts
Any better ideas are welcome ...
@karelhala @martinpovolny @Hyperkid123
=> Fix linter issues in specs

src/dialog-editor/services/dialogEditorService.spec.ts, src/dialog-editor/services/dialogEditorService.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1557488
Steps to reproduce:
1. Import the dialog that has one `null` value like one below and edit the dialog
2. Edit the location element and click on options tab.
3. The `Load values on init` button is half cut (it doesn't have `true`/`false` value)
```
---
- description: 
buttons: submit,cancel
label: dynamic_refresh
blueprint_id: 
dialog_tabs:
- description: 
display: edit
label: Tab
display_method: 
display_method_options: 
position: 0
dialog_groups:
- description: 
display: edit
label: Box
display_method: 
display_method_options: 
position: 0
dialog_fields:
- name: contract
description: 
data_type: string
notes: 
notes_display: 
display: edit
display_method: 
display_method_options: {}
required: true
required_method: …
```
=> Return correct value from anyDialogFields

webpack.config.js
The first commit literally just cleans up formatting, whitespace, etc. and moves all the code inside the exported function, instead of ignoring environment in the first parts.
The second adds `watchOptions.ignore` to ignore vim swapfiles when running `webpack --watch`.
=> Webpack.config - clean up formatting, support vim

src/toolbar/components/toolbar-menu/toolbar-list.html, src/toolbar/components/toolbar-menu/toolbarListComponent.ts
When there's a toolbar dropdown with all child items disabled, it is not possible to open it. Each disabled toolbar button contains a hint about why it is disabled if you hover on it. These two things don't really fit together as you are not able to hover onto a disabled child element in a dropdown if all the other child elements are disabled.
My solution is to, if it is necessary, collect all the tooltips from the child items and display them inside the tooltip of the parent element.
@miq-bot add_reviewer @karelhala 
@miq-bot add_reviewer @Hyperkid123 
@miq-bot add_label toolbars, hammer/no, ux/review
Fixes https://github.com/ManageIQ/manageiq/issues/18460
=> Squash tooltips from child elements in toolbar dropdown if disabled

src/dialog-user/services/dialogData.ts
This change is correcting a test for emptiness of a service dialog field.
The problem now is the button to submit the form is disabled, because the field with validation is treated as not empty (`fieldValue` is of value `null`) and therefore with invalid value.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692736
=> Corrected condition testing emptiness of dialog field

src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
The UI wasn't changing the validation rule for text boxes when a new rule would come through via automate. This should fix that.
I also updated the message to actually include the regex that the user should match against, otherwise the user is simply guessing at what their "invalid format" is. I'm guessing maybe we had a reason to obscure the regex before, so if that is the case, it can easily be left out of this PR.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1694737
@miq-bot add_label bug, hammer/yes
/cc @tinaafitz Can you comment on the validation message change?
=> Allow validator_rule to be updated in case of dynamic text boxes

src/dialog-editor/components/modal-field-template/dynamic-values.html, src/dialog-editor/components/toolbox/toolboxComponent.ts
Depends on:
* schema: https://github.com/ManageIQ/manageiq-schema/pull/357 (merged)
* core: https://github.com/ManageIQ/manageiq/pull/18600 (merged)
Dynamic dialog fields can load on init (once), by manually triggering a refresh button, or from "fields to refresh".
Before, when there was no refresh button, load on init was hardcoded to true on the model side and the switch was hidden.
This makes the "Load Values on Init" switch always visible, independent of "Show Refresh Button".
https://bugzilla.redhat.com/show_bug.cgi?id=1684575
=> Dialog editor: Make "Load Values on Init" independent of "Show Refresh Button" 

src/dialog-editor/components/modal-field-template/date-time-control.html
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692980
=> Allow datepicker field in service dialogs to be set as required

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.ts
Using dialogField.value for fields that are not a subclass of `DialogFieldSortedItem`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1696474
=> Fix for dynamic dialog fields not being updated 

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.ts
After some deliberation, we decided it doesn't really make sense to change the `ng-model` designation since "values" doesn't make sense for a non sorted field that doesn't actually have a list of multiple values. Instead, the `ng-model` changes will be reverted and we will ensure the back end passes through the `"default_value"` properly for dynamic non sorted fields. That PR can be [found here](https://github.com/ManageIQ/manageiq/pull/18650)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698586
/cc @himdel
=> Revert ng-model changes from #381

src/dialog-editor/components/modal-field/modalFieldComponent.ts
it's not a fully qualified *domain* name, just a name, the db field is `fqname`.
This just renames a local variable to prevent confusion. No effect whatsoever.
@miq-bot add_label technical debt, hammer/no
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1553846
=> Dialog editor endpoint selection - fix badly named fqdn to fqname

src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts
This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1706693.
Basically, we made [this change](https://github.com/ManageIQ/manageiq/pull/18650) but neglected to change the ui-components side on refresh callback, so it was still using the old `values` but that key no longer was being returned.
@himdel Please Review
=> Replace 'values' key with 'default_value' when updating value for field

package.json
Make sure `:main` in `package.json` points to correct file so `@manageiq/ui-components` can be moved from asset pipeline to webpack
@miq-bot add_label technical debt, hammer/no, changelog/no
=> Make sure main points to correct file

package.json, src/dialog-user/index.ts, src/styles/vendor.scss, src/vendor.ts
Removing `ui-select` as mentioned in https://github.com/ManageIQ/manageiq-ui-classic/pull/5607#issuecomment-497364608
> LGTM, except it seems this is dead.
>
>ui-select was added in ui-classic in 8fd8d7b, "to match ui-components". (ui-classic has never used ui-select directly it seems)
>
>ui-componens did use ui-select in dialog-user, until ManageIQ/ui-components@5fcb88d (ManageIQ/ui-components#249), where it was replaced by pf-select (and later miq-select).
>
>Can you change this to remove ui-select please? :) (also from ui-components)
@miq-bot add_label dependencies, hammer/no, changelog/no
=> Remove ui-select that is no longer used

src/dialog-editor/components/index.ts, src/dialog-editor/components/modal-field-template/text-area-box.html, src/dialog-editor/components/modal-field-template/text-box.html, src/dialog-editor/components/validation/index.ts, src/dialog-editor/components/validation/validation.html, src/dialog-editor/components/validation/validation.ts, src/dialog-editor/index.ts
1. Create a Dialog with text box validation button
2. Give a validation Regex expression
3. Move the button 'No'
Actual results:
it will be again halfway between Yes and No when the user opens the dialog editor next time.
Expected results:
It should be either Yes/No as per previously saved data
--- 
This is caused by the switch using `ng-true-value="'regex'" ng-false-value="undefined"`, together with angular-bootstrap-switch assuming that `null` and `undefined` always mean "not sure" (https://github.com/frapontillo/angular-bootstrap-switch/issues/138)
Changing to use "false" for no validator type. (And to automatically convert null/undefined to false when editing.)
---
Also moved the 4 copies of the switch + regex input to a separate component, and sorted the requires, …
=> Dialog editor - fix Validate switch undecided value

src/dialog-editor/components/modal/modalComponent.ts, src/dialog-editor/components/tab-list/tabListComponent.ts, src/dialog-editor/services/dialogEditorService.spec.ts, src/dialog-editor/services/dialogEditorService.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1707961
The dialog's content is saved into `sessionStorage` while the editor is getting initialized.
Every change should update the content of the saved dialog.
In the `sessionStorage` the dialog is stored under key `service_dialog-new` or `service_dialog-{id}`.
The dialog is removed from the `sessionStorage` if the dialog is submitted, of user confirms he want's to abandon the changes.
In case the user gets unintentionally redirected, an option to restore the changes will be offered.
This PR contains mostly the calls to update the dialog after the change is done.
Links
----------------
* https://github.com/ManageIQ/manageiq-ui-classic/pull/5612
* https://bugzilla.redhat.com/show_bug.cgi?id=1707961
Steps for Testing/QA …
=> Use sessionStorage to avoid loss of unsaved dialog

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1713646
As the ng-model does not use attribute 'values' but 'default_value',
the correct value was not getting updated and checkbox had always
received 'undefined'.
After removing the test working with the obsolete attribute,
checkbox gets updated correctly again.
=> Removed methods working with obsolete attribute

src/dialog-user/components/dialog-user/dialogField.html, src/miq-select/index.ts, src/miq-select/miqOptions.js
(extracted from https://github.com/ManageIQ/ui-components/pull/379)
This adds a `miq-options` directive to allow using `ng-options` and setting additional attributes (`data-tokens`) on the generated `<option>` elements.
And it changes dialog-user dropdowns to use these => numeric values should be supported in dropdowns now.
=> DialogUser dropdowns - support integer keys

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1721814
The dialog-user component is only looking at `validator_rule`, not `validator_type`.
Thus, it attempts to run regex validation even when validation is disabled.
This is a follow-up to https://github.com/ManageIQ/ui-components/pull/388 which changed `validator_type` from `undefined` to `false` when disabled. `false` gets saved by automate as `"f"`, which is not falsy.
=> Dialog user - only run regex validation when validator_type is set to regex

src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692863
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1702497
Steps to Reproduce from BZ ticket:
1. create a new service dialog with a datepicker field
2. add the service dialog to the catalog
3. in the service catalog select the service dialog and click on order
4. Clear the date from the field and enter "test" in the datepicker field
=> Mark datepicker field as valid only if it's value is an instance of Date

src/dialog-editor/components/modal-field/modalFieldComponent.ts, src/dialog-editor/components/tree-selector/tree-selector.html
If the domain prefix is included in the automate entry point for a dialog element, it is possible to select the right node in the tree selector. 
@miq-bot add_reviewer @himdel 
cc@pkomanek
@miq-bot add_label bug, hammer/no
https://bugzilla.redhat.com/show_bug.cgi?id=1553846
=> Allow the selection of a node in DialogEditor + TreeSelector

src/dialog-user/components/dialog-user/dialogField.spec.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Introduced in https://github.com/ManageIQ/ui-components/pull/394,
we now require `default_value`'s type to match the types of keys in `values`.
But:
* the API never returns a non-string `default_value` - we have to do the conversion to the right type.
For multiselects, the value is JSON-encoded and preserves types,
but for single select, even integer values get passed as strings.
* we want to explicitly support converting the keys in `values` to the right type
So now, all of these get converted (on load) to the type in `data_type`:
* `default_value` for single-selects
* each value in `default_value` for multi-selects
* each `value[0]` from `values` for all selects
The conversion rules are as follow:
* if `data_type` is `string`:
* `null` or `undefined` (actual nil values, not strings) get …
=> DialogUser - convert single-select default_value to the right data_type

src/dialog-user/components/dialog-user/dialogField.html, src/dialog-user/components/dialog-user/dialogField.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
Fixes some fallout from #399 and some earlier issues:
* date & date&time required fields would now fail validation when filled in, because dates are considered empty `_.isEmpty(new Date()) === true`
* date&time could not get cleared `Cannot read property 'getFullYear' of null`
* date, date&time, and other fields were missing the validation message when failing validation
* cleared date or date&time would fail validation even when not required
Now,
date & date&time should behave the same,
both go to `null` when cleared,
both fail validation when `null` and required,
neither fail validation when non-null or not required.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728600
Cc @eclarizio , @romanblanco
=> Dialog user - fix validation for date & date&time when field is required; clearing the fields

src/dialog-editor/components/tab-list/tabListComponent.ts
It does not make sense to create a new tab without a content, with adding a new section, user can drag&drop new Dialog Fields right after creating a new tab.
=> Add a section with creating a new tab

src/gtl/components/tile-view/tile-view.html, src/styles/ui-components.scss
This PR removes the gray background from the tile view and adjusts the card styling to help it stand out on a white background.
Follow-up PR here: https://github.com/ManageIQ/manageiq-ui-classic/pull/5917
Issue #406
Old
new
=> tile view styling update

src/dialog-editor/services/dialogValidationService.spec.ts, src/dialog-editor/services/dialogValidationService.ts
in UI of the dialog editor we're hinting users to "add a section", but the error messages used a term "group".
=> Replaces 'group' with 'section' for consistency

src/dialog-editor/services/dialogValidationService.ts
Adding a Tag control without chosing a category should fail dialog editor validation.
Previously, this didn't work because it's set to `""` not `null` when unset, and it's `field.options.category_id`, not `field.category_id`.
Now, the validation will fail with "'Category needs to be set for TagControl field".
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1729265
---
The problem with that ^ is that we never actually show the validation message anywhere.
We're trying to show it on the submit button in ui-classic, but the button is disabled (and thus not rendering title) when validation fails.
=> Moving validation to the top of the dialog, together with https://github.com/ManageIQ/manageiq-ui-classic/pull/5938 (or https://github.com/ManageIQ/manageiq-ui-classic/pull/5922 for the future) …
=> Dialog editor - validate tag category

src/dialog-user/components/dialog-user/dialogField.html
the model is using a Date object,
but we want the display date to use the US date format for consistency
(instead of the 2019-07-31 default)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728964
=> Dialog User - use m/d/y for showing dates, instead of iso

package.json
Fixes #411
Now, `yarn` works even with v12.8.0 :).
Cc @romanblanco
=> Update node-sass to a version that support node 12

src/dialog-user/components/dialog-user/dialogField.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729379
setting the default_value on `<None>` in case no default_value has been set to avoid getting an empty field that breaks the dropdown functionality
=> Correct dropdown choices for tag control in Dialog User

src/dialog-user/components/dialog-user/dialogField.ts, src/dialog-user/services/dialogData.ts
(follow-up to #412)
The dialogField component should not be changing default_value,
the dialogData service is the place where default_value gets set.
Otherwise, validations from dialog-user and from dialog-field will work with different values, which can cause invalid validations or validation loops.
(docs - https://github.com/ManageIQ/manageiq-ui-classic/wiki/Dialogs#dialog-user-tidbits)
https://bugzilla.redhat.com/show_bug.cgi?id=1729379
Cc @romanblanco @h-kataria
=> dialog-user: Move tagging fix from #412 to setDefaultValue

src/toolbar/components/toolbar-menu/toolbar-list.html
=> fix uib-dropdown according to documentation

src/dialog-user/services/dialogData.ts
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1670051
In case the `DateControl` or `DateTimeControl` field are not set as `required`, the added code tests if the entered value is a date or an empty field and therefore valid.
=> Validate content for non-required fields

src/styles/ui-components.scss
This PR removes the original PF3 toolbar styling overrides that have been duplicated in the React repo (https://github.com/ManageIQ/react-ui-components/blob/master/src/toolbar/styles.scss#L21), preventing styling updates.
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6317
=> Remove conflicting toolbar styling

src/dialog-user/components/dialog-user/dialogUser.ts, src/dialog-user/services/dialogData.spec.ts, src/dialog-user/services/dialogData.ts
(This won't affect anything without the changes in https://github.com/ManageIQ/manageiq-ui-service/pull/1595 and https://github.com/ManageIQ/manageiq-ui-classic/pull/6291, merge this one first.)
Problem:
date fields need to be a Date instance, for the date/datetime input to work
there is no explicit conversion from Date to string before submitting to the API
that Date objects gets serialized by converting to a UTC datetime string,
which gets cut to 10 charecters on the backend,
and in UTC+N timezones, that leads to "2019-10-17 0:00 local" being submitted as "2019-10-16T(24-N):00:00Z" and cut to "2019-10-16" which is off by one.
Solution:
provide a `DialogDate#outputConversion` function which will return dialog data in a format suitable for API submission,
make the UIs use it (separate …
=> DialogUser - use DialogData.outputConversion before submit and refresh

src/dialog-user/components/dialog-user/dialogUser.spec.ts, src/dialog-user/components/dialog-user/dialogUser.ts
when validator_type is set to 'regex' on load, the field will use the current validator_rule to validate,
but if validator_type is changed only later in a method, the field never starts to validate.
Making sure both validator_rule and validator_type are respected during field refresh.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1769960
=> DialogUser - update validator_type during field refresh

src/dialog-user/components/dialog-user/dialogField.html
Making it consistent with the dropdowns and making a step towards fixing https://github.com/ManageIQ/manageiq-ui-classic/issues/6392 and making https://github.com/ManageIQ/manageiq-ui-classic/pull/6400 less buggy.
=> Use miq-select in dialogUser's tagging fields

src/dialog-user/services/dialogData.ts
Have a dropdown with integer data_type,
have the values set so that one value is 0,
select that value as default value. (in dialog editor or the dialog field yaml)
Loading the dialog, `default_value: '0'` comes from the server,
`DialogData#setDefaultValue` converts it to numeric `0`, based on the data type,
but when it gets called again, the numeric `0` fails a falsy check, and the first option in the list gets used instead.
Adding a `data_type === 'integer'`, `default_value === 0` exception to the falsy check.
(A better but also much larger fix would be to refactor dialog user so that `setDefaultValue` never gets called twice on the same data.)
Before:
```
numReq old 0 string
new 0 number
numOpt old 0 string
new 0 number
strReq old 0 string
new 0 string
strOpt old 0 string
new 0 string …
```
=> dialog-user: fix integer dropdown 0 default_value handling

src/dialog-user/services/dialogData.ts
right now, field.default_value gets initialized to 0 for every DialogFieldTagControl.
What should be happening:
- single selects:
`<Choose>`/`<None>` gets shown as default
- multiselects:
`Nothing selected`
same as the other dropdowns and multidropdowns.
Thus changing the initialization to set either "" or [] as default_value.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6392
May depend on https://github.com/ManageIQ/manageiq/pull/19696 ~~and https://github.com/ManageIQ/manageiq/pull/19697~~
=> Dialog User - set default value for tag controls

src/miq-select/miqSelect.js
Prevent the select from focusing the search input on actions like selecting an option.
This makes it possible to unselect multiple items in a row, even when scolled down.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7010
=> miq-select: default liveSearchFocus to false

src/dialog-user/services/dialogData.ts, tslint.json
Regex validation in the browser depends on the browser supporting the regex,
when using negative lookbehind, which is not supported in Firefox <78,
it just logs an error in the console:
now, it also shows a message
(when the feautre is supported, no effect)
Related: https://github.com/ManageIQ/manageiq-ui-classic/issues/7050
=> dialogData#validateField - fail validation when regex is not supported by browser

src/dialog-user/services/dialogData.ts
1. create a service dialog with two radio buttons: one of the doesn't have default value set, the other one does
2. create a catalog item that uses the above service dialog
3. try to order the service
Without this fix, the field with no default value would always default to the first choice.
With this fix in place, the no default value is being honored.
https://bugzilla.redhat.com/show_bug.cgi?id=1713212
=> Don't set default value for non-applicable fields

src/dialog-editor/components/abstractModal.ts, src/dialog-editor/components/modal-box/box.html, src/dialog-editor/components/modal-box/modalBoxComponent.ts, src/dialog-editor/components/modal-field/field.html, src/dialog-editor/components/modal-field/modalFieldComponent.ts, src/dialog-editor/components/modal-tab/modalTabComponent.ts, src/dialog-editor/components/modal-tab/tab.html, src/dialog-editor/components/modal/modalComponent.ts, src/dialog-editor/services/dialogValidationService.ts
This PR implements field, tab & box level validation when creating / editing field, tab & box in current dialog editor. Should a particular validation fail, the `Save` button will be disabled and button title will be set with the validation message. Previously, the validation would take place on the service dialog level, which seemed counter-intuitive.
Field validation example:
Box validation example:
Tab validation example:
https://bugzilla.redhat.com/show_bug.cgi?id=1741633
=> Add support for local validation of box, tab and field

src/dialog-editor/components/modal-field-template/drop-down-list.html, src/dialog-editor/components/modal-field-template/tag-control.html
1. create a new service dialog, add a single value dropdown
2. select a default value for the dropdown: instead of selected value, the dropdown would render `Nothing Selected`
3. select the same default value again: this time the dropdown will honor and render the selected default value
I think rendering `Nothing Selected` in a single value dropdown is unnecessary and confusing. We already add a `None / "") value to single value dropdowns and it already represents `Nothing Selected`. Removing the `Nothing Selected` label will work-around the weird dropdown behavior described above.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1713205
=> Don't print "Nothing Selected" in single value dropdown

src/dialog-user/components/dialog-user/dialogField.html
This is ivanchuk version of https://github.com/ManageIQ/ui-components/pull/427
We need it in ivanchuk to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1859524
=> [IVANCHUK] Use miq-select in dialogUser's tagging fields

src/dialog-user/services/dialogData.ts
This is what `data.values` for single-value `DialogFieldDropDownList` looks like:
```
Array(4)
0: (2) [null, "<None>"]
1: (2) ["1", "One"]
2: (2) ["3", "Three"]
3: (2) ["2", "Two"]
length: 4
__proto__: Array(0)
```
This is what `data.values` for single-value `DialogFieldTagControl` looks like:
```
Array(5)
0: {id: null, name: "<None>", description: "<None>"}
1: {id: "3", name: "chicago", description: "Chicago"}
2: {id: "4", name: "london", description: "London"}
3: {id: "2", name: "ny", description: "New York"}
4: {id: "5", name: "paris", description: "Paris"}
length: 5
__proto__: Array(0)
```
Setting the `null` default value for these cases will make the `Nothing Selected` thing go away.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1861252
=> Correctly set 'null' default value for TagControl & Dropdown

tslint.json
On master, this was part of https://github.com/ManageIQ/ui-components/pull/441,
now backporting https://github.com/ManageIQ/ui-components/pull/447 to jansa caused travis to [go red](https://travis-ci.com/github/ManageIQ/ui-components/builds/178817018),
Removing the line lenght limit for previous releases (both, 447 is ivanchuk/yes).
Fixes travis.
(This is an alternative to backporting the whole PR, https://github.com/ManageIQ/ui-components/pull/441#issuecomment-670531704)
=> [JANSA] tslint: remove line lenght limit

src/dialog-editor/components/field/field.html, src/dialog-editor/components/field/fieldComponent.ts
This change is for dialog editor to honor sorting options of dropdown & radio button fields:
* sort either by key or by value
* sort values either as strings or as integers
Needs to go in with https://github.com/ManageIQ/manageiq-ui-classic/pull/7202
https://bugzilla.redhat.com/show_bug.cgi?id=1740878
=> Honor sorting parameters in dialog editor

src/gtl/components/data-table/data-table.html
This issue was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/7189 Issue existed on the lists with no checkboxes/icons. Table headers were shifted on such screens.
before
after
=> Fixed table header shift after icon column was removed from list view

src/dialog-user/services/dialogData.ts
1. create a service dialog with integer-type values, make sure `0` is among them
2. make sure the data type is set to integer and that `0` is set as default value
3. create a catalog item with the above service dialog
4. order the catalog item and observe the form
before
after
Previously, `0` as default value would be incorrectly interpreted as no default value.
https://bugzilla.redhat.com/show_bug.cgi?id=1878103
=> Correctly set null as default value for null and empty strings

src/styles/dialog-editor-toolbox.scss, src/styles/dialog-editor.scss
Found in: Automation -> Automate -> Customization -> Service Dialogs
Fixes: https://github.com/ManageIQ/ui-components/issues/453
Preview:
=> Modified CSS to Prevent Truncation Issue in Certain Locales

src/dialog-editor/components/modal-field-template/drop-down-list.html, src/dialog-editor/components/modal-field/modalFieldComponent.ts, src/dialog-editor/components/modal/modalComponent.ts, src/dialog-editor/components/tree-selector/tree-selector.html, src/dialog-editor/services/dialogValidationService.ts, src/dialog-user/services/dialogData.ts, src/styles/dialog-editor-boxes.scss, src/styles/ui-components.scss
Screenshots in related PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/8844
=> Introducing embedded_workflow to dynamic select box in service dialogs

src/dialog-editor/components/abstractModal.ts, src/dialog-editor/components/modal-field/field.html, src/dialog-editor/components/modal-field/modalFieldComponent.ts, src/dialog-editor/components/modal/modalComponent.ts, src/dialog-editor/services/dialogValidationService.ts, src/styles/ui-components.scss
Before -
https://github.com/ManageIQ/ui-components/assets/87487049/f9b88090-1e73-45d6-94b2-b31f8a2a7ad8
- Edit a service dialog, 
- Click edit field to open the options modal box
- Change a field name to an already used name (duplicate name)
- Click save at the options modal box
- Click save at the service dialog form
- We will get a warning that the field name cannot be used.
- cancel the form.
- select the service dialog again and edit it
- check the field name of the field where you tried to put a duplicate name.
- See that the field name got updated and now we have a duplicate field.
After
https://github.com/ManageIQ/ui-components/assets/87487049/f3b8c739-6b52-45b3-92f2-8278d54fc7d2
- The options modal box will check for duplicate field names
- If there are duplicate field names, the …
=> Fix for duplicate field names and render validation messages for server
